serde-rs/serde

- serde2/serde2_macros/src/lib.rs
- serde2/src/json/ser.rs
- serde_macros/src/lib.rs
- src/json/ser.rs
This PR contains the changes to std::num currently.
> I expect to add the changes of the second pass stabilization of std::string very soon.
String stabilization commit added.
> Follow changes in std / rustc

- serde2/serde2_macros/src/lib.rs
Allow specification of an alias on a struct field with
the #[serde(alias="SomeAlias"] attribute.
Addresses #13
Depends on https://github.com/erickt/rust-serde/pull/21
> Add aliases on struct fields

- src/de/impls.rs
- src/ser/impls.rs
Expand a few, add some new ones, etc.
> Tweak some Deserialize/Serialize impls

- src/json/ser.rs
It didn't compile for me without this change.
> Fix compilation for latest nightly

- serde_macros/src/de.rs
- serde_macros/src/field.rs
- tests/test_json.rs
> missing field errors displayed original field name instead of renamed

- src/json/de.rs
This has a non-trivial performance effect due to the branch prediction, but is expected to be no slower than the older code and, at least in some cases, is slightly faster for a string-heavy JSON. In my local machine it was about 4% faster.
> Replace a redundant `escape` variable with nested matches.

- benches/bench_log.rs
- src/de/impls.rs
- src/de/mod.rs
- src/iter.rs
I'm starting to work on a separate crate at https://github.com/oli-obk/serde-xml
cc #39 
cc #68
> changes needed for xml parsing

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
I found (de)serializing `Cow` to be useful after working with rustc-serialize and found myself missing the same impls in Serde.
> Add impls for Cow

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
> Implement serialization for `Result`.

- serde/src/json/ser.rs
- serde_tests/tests/test_json.rs
> Fix serializing maps/sequences with no size hint

- serde_codegen/src/ser.rs
- serde_tests/tests/test_macros.rs
> Fix deriving traits for fully generic types.

- serde_codegen/src/attr.rs
- serde_codegen/src/de.rs
- serde_codegen/src/field.rs
- serde_codegen/src/ser.rs
- serde_tests/tests/test_annotations.rs
Closes #99 
cc @kostya: Is this what you're looking for?
> Add `#[serde(skip_serializing)] to skip serializing some fields

- serde/src/de/mod.rs
- serde/src/ser/mod.rs
- serde_codegen/src/de.rs
- serde_codegen/src/ser.rs
- serde_json/src/de.rs
- serde_json/src/lib.rs
- serde_json/src/ser.rs
- serde_json/src/value.rs
- serde_tests/tests/test_bytes.rs
- serde_tests/tests/test_json.rs
- serde_tests/tests/test_macros.rs
- serde_tests/tests/test_ser.rs
> tuple enums with single element should not be a json-array

- serde_json/src/de.rs
- serde_tests/tests/test_json.rs
> Rewrite json parser to not require consuming the full stream

- .travis.yml
- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_json/Cargo.toml
- serde_json/src/de.rs
- serde_macros/Cargo.toml
> Fix doc links, recover some json deserialization speed 

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde_json/src/value.rs
This improves error handling to match the needs of msgpack
> Add Error::length_mismatch, Error::type_mismatch, and de::Type

- README.md
Might be worthwhile to look at trying to automate testing the code in
the README (perhaps by generating the README from some special tests).
> readme: fix example code so it builds

- .gitignore
> chore(git): Ignore swap files

- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde_tests/benches/bench_enum.rs
- serde_tests/benches/bench_map.rs
- serde_tests/benches/bench_struct.rs
- serde_tests/benches/bench_vec.rs
- serde_tests/tests/test_bytes.rs
- serde_tests/tests/token.rs
> Have serde::de::Error require std::error::Error

- README.md
- serde/src/de/impls.rs
- serde_codegen/src/attr.rs
- serde_codegen/src/de.rs
- serde_codegen/src/field.rs
- serde_tests/tests/test_annotations.rs
- serde_tests/tests/test_de.rs
- serde_tests/tests/token.rs
* Added codegen for disallow_unknown
* ... with new default to ignore unknown values during deserialization
* Added ContainerAttrs
Original pull request against v0.6.x: https://github.com/serde-rs/serde/pull/201
> Implemented disallow_unknown

- serde_codegen/src/de.rs
- serde_codegen/src/ser.rs
This also improves the error spans when there's an internal
error.
Closes #206.
> feat(errors): Don't panic if annotating a non-struct/enum

- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_codegen/src/de.rs
- serde_macros/Cargo.toml
- serde_tests/Cargo.toml
fixes https://github.com/serde-rs/serde/issues/235
> Update serde_codegen for rustc 1.8.0-nightly (ce4b75f25 2016-02-12)

- serde/src/de/mod.rs
- serde_codegen/src/de.rs
- serde_tests/tests/test_de.rs
- serde_tests/tests/token.rs
> feat(de): Add an Error::unknown_variant error.

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
- serde_tests/tests/test_de.rs
- serde_tests/tests/test_ser.rs
> feat(impls): Add impls for std::net::Ip{,v4,v6}Addr

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
- serde_tests/tests/test_de.rs
- serde_tests/tests/test_macros.rs
- serde_tests/tests/test_ser.rs
- serde_tests/tests/token.rs
> feat(serde): Add hooks for fixed-sized arrays

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
This should implement Serialize and Deserialize for PhantomData. I have not been able to find unit tests, so I can't be 100% sure, though.
> Resolves #183 - Serialize and Deserialize for PhantomData

- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_macros/Cargo.toml
- serde_tests/Cargo.toml
🎊 Thanks so much for everyone's work getting this out! 🎊
> feat(cargo): Version bump to 0.7!

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/ser/mod.rs
- serde_codegen/src/attr.rs
- serde_codegen/src/de.rs
- serde_codegen/src/ser.rs
- serde_tests/benches/bench_enum.rs
- serde_tests/benches/bench_map.rs
- serde_tests/benches/bench_struct.rs
- serde_tests/benches/bench_vec.rs
- serde_tests/tests/test_bytes.rs
- serde_tests/tests/token.rs
> Rename error trait methods, optimize bytes, don't expose primitive

- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/ser/mod.rs
- serde_tests/benches/bench_enum.rs
- serde_tests/benches/bench_map.rs
- serde_tests/benches/bench_struct.rs
- serde_tests/benches/bench_vec.rs
- serde_tests/tests/test_bytes.rs
- serde_tests/tests/token.rs
> feat(errors): Switch Error::custom to use Into<String>

- README.md
~~Not very useful as just a badge, but a great way to find odd things in our code.~~
We already run against clippy in travis... Just a badge then... Who doesn't like badges?
> add clippy badge

- README.md
"skip_serializing_if" means do not serialize if **true**.
> Fix documentation of skip_serializing_if

- serde_codegen/src/bound.rs
- serde_codegen/src/de.rs
- serde_codegen/src/ser.rs
- serde_tests/tests/test_macros.rs
> fix(codegen): Discard type defaults from impl generics

- examples/serde-syntex-example/Cargo.toml
- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_macros/Cargo.toml
- serde_tests/Cargo.toml
Let's get this out ASAP to fix the regression in 0.7.4: #305. Currently blocking https://github.com/benashford/rs-es/issues/65.
> Release 0.7.5

- serde/src/bytes.rs
- serde/src/de/impls.rs
- serde_codegen/src/de.rs
- serde_tests/benches/bench_enum.rs
- serde_tests/benches/bench_struct.rs
- serde_tests/tests/test_de.rs
> Remove unused imports and needless borrows

- serde_codegen/src/de.rs
This combines `deserialize_newtype_struct`, `deserialize_tuple_struct`, and `deserialize_tuple_variant` into a single method `deserialize_tuple`, as well as `deserialize_struct` and `deserialize_struct_variant` into a single method `deserialize_struct`. No behavior changes.
> Reduce code duplication in Deserialize generator

- serde_codegen/src/bound.rs
- serde_tests/tests/test_gen.rs
> Strip more references

- serde/src/de/mod.rs
> Better documentation for de::Error::invalid_length

- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_macros/Cargo.toml
- serde_tests/Cargo.toml
> Rustup too rustc 1.11.0-nightly (7746a334d 2016-05-28)

- CHANGELOG.md
- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_macros/Cargo.toml
This filters out junk files from the crates.
Closes #331.
> Add "include" to Cargo.toml files

- serde/Cargo.toml
- serde/src/de/mod.rs
- serde/src/ser/mod.rs
- serde/src/utils.rs
- serde_codegen/Cargo.toml
- serde_macros/Cargo.toml
I should probably yank 0.7.6, too
cc @alexcrichton this should unbreak your setup, sorry about that.
> undo the breaking change introduced in 0.7.6

- serde_codegen/src/attr.rs
- serde_tests/tests/test_annotations.rs
- serde_tests/tests/test_gen.rs
> Fix attributes canceling each other

- examples/serde-syntex-example/README.md
> Use rustup in serde-syntex-example instead of multirust

- .travis.yml
- examples/serde-syntex-example/src/main.rs
> Fix nightly check in serde-syntex-example

- .travis.yml
Syntex no longer supports this version of Rust.
> Stop building on 1.5.0

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
- serde_macros/Cargo.toml
- serde_tests/Cargo.toml
- serde_tests/tests/macros.rs
- serde_tests/tests/test_de.rs
- serde_tests/tests/test_ser.rs
> De/serialize for HashMap<K, V, S> and HashSet<T, S>

- serde_codegen/src/bound.rs
Per https://github.com/serde-rs/syntex/issues/70 we no longer support <1.7.
> Remove filter no longer necessary for rustc >=1.7

- serde_codegen/src/de.rs
- serde_codegen/src/lib.rs.in
- serde_codegen/src/ser.rs
- serde_codegen/src/span.rs
- serde_macros/Cargo.toml
- serde_macros/tests/compile_tests.rs
- serde_macros/tests/run-pass/identity-op.rs
Fixes #350 and fixes https://github.com/Manishearth/rust-clippy/issues/969.
> Record expansion info

- serde_codegen/src/de.rs
Equivalent to what #422 does for maps.
> Close the seq before failing on invalid length

- serde_codegen/src/lib.rs
> Remove public dependency on Syntex

- README.md
> Mention Empty Bounds for Recursion in Readme

- README.md
To prevent people from copy-pasting this. Also see https://github.com/serde-rs/json/pull/124
> Set explicit versions in Readme

- README.md
- serde_macros/Cargo.toml
- serde_macros/build.rs
- serde_macros/tests/skeptic.rs
- serde_macros/tests/test.rs
supersedes #255 
fixes #474, #255
> use skeptic to test the readme and fix readme for 0.8

- README.md
> fix an example in the README

- README.md
[Rendered](https://github.com/serde-rs/serde/blob/affc81b1d65a4503e18f22e09b11702658a5012c/README.md)
> Getting help

- examples/serde-syntex-example/Cargo.toml
- serde/Cargo.toml
- serde_codegen/Cargo.toml
- serde_codegen_internals/Cargo.toml
- serde_macros/.cargo/config
- serde_macros/Cargo.toml
- serde_macros/tests/run-pass/identity-op.rs
- serde_test/Cargo.toml
- testing/Cargo.toml
~~Blocked on https://github.com/serde-rs/aster/pull/101 and https://github.com/serde-rs/quasi/pull/57.~~
> Update syntex to 0.41

- serde_codegen/src/de.rs
- testing/tests/test_gen.rs
> Fix codegen with lifetimes but no type parameters

- serde/Cargo.toml
- serde/src/de/value.rs
- serde_codegen/Cargo.toml
- serde_codegen_internals/Cargo.toml
- serde_codegen_internals/src/attr.rs
- serde_macros/Cargo.toml
- serde_macros/tests/run-pass/identity-op.rs
- testing/Cargo.toml
> Re-enable clippy

- serde/src/de/value.rs
@nox is this what you were trying to implement?
> Impl SeqVisitor for MapDeserializer

- serde_codegen/src/ser.rs
- testing/tests/test_macros.rs
> Make serde state variable unique by naming it __serde_state

- README.md
- examples/serde-syntex-example/src/main.rs
- serde_derive/Cargo.toml
- serde_derive/src/lib.rs
- serde_derive/tests/compile-fail/duplicate-attribute/rename-and-ser.rs
- serde_derive/tests/compile-fail/duplicate-attribute/rename-rename-de.rs
- serde_derive/tests/compile-fail/duplicate-attribute/rename-ser-rename-ser.rs
- serde_derive/tests/compile-fail/duplicate-attribute/rename-ser-rename.rs
- serde_derive/tests/compile-fail/duplicate-attribute/rename-ser-ser.rs
- serde_derive/tests/compile-fail/duplicate-attribute/two-rename-ser.rs
- serde_derive/tests/compile-fail/str_ref_deser.rs
- serde_derive/tests/compile-fail/unknown-attribute/container.rs
- serde_derive/tests/compile-fail/unknown-attribute/field.rs
- serde_derive/tests/compile-fail/unknown-attribute/variant.rs
- serde_derive/tests/run-pass/identity-op.rs
- serde_derive/tests/test.rs
> Rename rustc_macro to proc_macro

- serde/src/de/impls.rs
- Fixes #582
- Fixes #583
- Combines the ArrayVisitor* types into one ArrayVisitor like you suggested in #579; can't do the same for the TupleVisitor*s because those are public
- Removes noise from the `array_impls!` and `tuple_impls!` macros
> Array and tuple deserialization cleanup

- .travis.yml
Has not been uploading for months.
> Drop coveralls

- serde_codegen/Cargo.toml
- serde_codegen/src/lib.rs
cc https://github.com/dtolnay/quote/issues/14
> Do not copy tokens to String after expanding

- serde_codegen/src/ser.rs
- serde_codegen_internals/src/attr.rs
- testing/tests/test_ser.rs
> Implement skip_serializing for enum variant

- serde/src/bytes.rs
- testing/tests/test.rs.in
- testing/tests/test_bytes.rs
> Support deserializing ByteBuf from string

- serde_codegen/src/de.rs
- testing/tests/test_de.rs
> Stop generating visit_usize and visit_bytes for FieldVisitor

- testing/tests/test.rs
- testing/tests/test_gen.rs
> Add test for non ascii idents

- serde/src/lib.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
- testing/tests/test_ser.rs
> add wrapper to serde that allows serializing iterators as sequences

- .travis.yml
- serde/src/bytes.rs
- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde_codegen/src/de.rs
- serde_test/src/de.rs
Fixes #656.
I need to think more about this and also update serde_json before merging.
> Remove SeqVisitor::end() and MapVisitor::end()

- serde/src/bytes.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/macros.rs
- serde_test/src/de.rs
- serde_test/src/token.rs
- testing/tests/test_bytes.rs
> add missing `Vec<u8>` deserialization hint to `Deserializer`

- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde_test/src/de.rs
I went with the name `DeserializeSeed` for the trait but we can discuss. It contains the word "Deserialize" to suggest that it is analogous to the Deserialize trait. I want to avoid anything ending in "-er" like "Initializer" because those sound more similar to Deserializer. I used the word "Seed" rather than "State" to highlight the unique property of this trait which is we can start with some piece of data up front, whereas "state" places more emphasis on mutating the data along the way which is something Deserialize can do just as well.
Fixes #650.
> Stateful deserialization

- serde/src/de/impls.rs
> Suppress warning about using num::Zero

- serde/src/de/impls.rs
This is equivalent to #671 but for this hardcoded Deserialize impl.
> Remove visit_usize from Duration impl

- .travis.yml
- serde/src/export.rs
- serde/src/lib.rs
- serde_codegen/src/de.rs
- serde_codegen/src/ser.rs
- serde_derive/no-std-tests/Cargo.toml
- serde_derive/no-std-tests/src/main.rs
> Support serde_derive on no_std

- serde/Cargo.toml
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
- serde_codegen/Cargo.toml
- serde_codegen/src/ser.rs
- serde_derive/Cargo.toml
- serde_derive/no-std-tests/Cargo.toml
- serde_test/Cargo.toml
- serde_test/src/ser.rs
- testing/Cargo.toml
Fixes #467. There is no performance difference.
> Serialize T by ref

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/private.rs
- serde/src/de/value.rs
- serde/src/macros.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
- serde_codegen/src/de.rs
- serde_test/src/de.rs
- serde_test/src/ser.rs
- serde_test/src/token.rs
- testing/tests/test_de.rs
- testing/tests/test_ser.rs
> Remove usize and isize from data model

- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
@nox wanted this for serde_urlencoded.
> SerializeMap::serialize_entry

- serde/src/de/value.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
> No tuple structs with private fields in public API

- serde/src/bytes.rs
- serde/src/de/content.rs
- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/private.rs
- serde/src/de/value.rs
- serde/src/error.rs
- serde/src/iter.rs
- serde/src/lib.rs
- serde/src/ser/impls.rs
- serde/src/ser/impossible.rs
- serde/src/ser/mod.rs
- serde/src/ser/private.rs
- serde/src/utils.rs
- serde_codegen_internals/src/ast.rs
- serde_codegen_internals/src/attr.rs
- serde_codegen_internals/src/ctxt.rs
- serde_derive/src/bound.rs
- serde_derive/src/de.rs
- serde_derive/src/ser.rs
- serde_test/src/assert.rs
- serde_test/src/de.rs
- serde_test/src/lib.rs
- serde_test/src/ser.rs
I think this is way better than last time we tried it.
Fixes #438.
> Use rustfmt

- serde_codegen_internals/src/attr.rs
- test_suite/tests/test_gen.rs
> Pair serialize_with and deserialize_with into one attribute

- serde/src/de/content.rs
- serde/src/de/private.rs
- serde_derive/src/de.rs
- test_suite/tests/test_macros.rs
> Deserialization of Haskell style enums

- serde_test/src/assert.rs
- serde_test/src/de.rs
- serde_test/src/error.rs
- serde_test/src/ser.rs
- serde_test/src/token.rs
Still WIP; don't merge yet.
My take at documenting `serde_test`. I was very confused how the tokens worked when I first got into it and think that it could use some documentation.
> Documentation for serde_test.

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
I'm not sure whether we really need to be able to deserialize from an array, but `Duration` supports that so I followed suit.
> Implement `Serialize`/`Deserialize` for `Range`

- serde/src/de/impls.rs
> Deserialize OsString on Windows

- serde/src/de/ignored_any.rs
- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde_derive/src/de.rs
> Make the built-in visitors private

- serde/src/ser/mod.rs
- serde/src/ser/private.rs
> Remove the no_std implementation of collect_str

- serde/src/de/ignored_any.rs
- serde_test/src/de.rs
- test_suite/tests/test_de.rs
> Stop ignoring error in assert_de_tokens_ignore

- serde_test/src/de.rs
- serde_test/src/ser.rs
- serde_test/src/token.rs
- test_suite/tests/test_annotations.rs
- test_suite/tests/test_borrow.rs
- test_suite/tests/test_bytes.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_macros.rs
- test_suite/tests/test_ser.rs
> Modernize serde_test Token names

- serde/src/de/impls.rs
- serde/src/ser/impls.rs
- test_suite/tests/test_gen.rs
> Relax impls for [T; 0]

- serde_derive/src/de.rs
- test_suite/tests/test_de.rs
> Remove conversion from empty seq to unit struct

- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/private/de.rs
- serde_test/src/de.rs
- test_suite/tests/test_value.rs
> Rename ValueDeserializer trait to IntoDeserializer

- serde/src/de/ignored_any.rs
- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/private/de.rs
- serde_derive/src/de.rs
- serde_test/src/de.rs
> Access traits

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/macros.rs
- serde/src/private/de.rs
- serde_derive/src/de.rs
- serde_test/src/de.rs
> Rename Deserializer::deserialize to deserialize_any

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/private/de.rs
- serde_test/src/de.rs
> Simplify size_hint to Option<usize>

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
> Add Serialize/Deserialize for std types that provide interior mutability

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/de/value.rs
- serde/src/macros.rs
- serde/src/private/de.rs
- serde/src/private/macros.rs
- serde/src/private/ser.rs
- serde/src/ser/impls.rs
- serde/src/ser/impossible.rs
- serde/src/ser/mod.rs
- serde_test/src/de.rs
- serde_test/src/ser.rs
- serde_test/src/token.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
> Remove seq_fixed_size in favor of tuple

- serde/src/ser/impls.rs
> Removed Deref impl for NonZero

- serde/src/de/impls.rs
- test_suite/tests/test_de.rs
From our IRC discussion. My first PR here, so let me know if anything's off at all!
> impl Deserialize for &'a Path

- serde/src/private/de.rs
- test_suite/tests/test_macros.rs
> Support borrowing within internally tagged enum

- serde_derive_internals/src/attr.rs
- test_suite/tests/test_annotations.rs
fixes #931
I added a combined skip field attribute.
If this looks fine, I'll add a combined skip variant attribute too.
> Add a combined skip attribute

- serde/src/de/value.rs
This adds two new types to the `de::value` module,
`BorrowedStrDeserializer` and `BorrowedBytesDeserializer`. A
`BorrowedStrDeserializer` is just like `StrDeserializer`, except the
lifetime of the string is tied to the lifetime of the deserializer. This
can be useful when, for example, deserializing into a
`HashMap<&str, &str>` when the keys/values are tied to the deserializer
itself.
The `BorrowedBytesDeserializer` has no analog, but it's the same as
`BorrowedStrDeserialize` except for `&[u8]` instead of `&str`.
> add borrowed value deserializers

- serde/src/ser/impls.rs
> Fix unused seq and map macros

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/lib.rs
- serde/src/ser/impls.rs
- serde/src/ser/mod.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
> Support std::time::SystemTime

- serde/src/de/impls.rs
> NonZero constructor now returns Option

- serde/src/ser/impls.rs
- test_suite/Cargo.toml
- test_suite/tests/test_ser.rs
> Serialize unsized Arc and Rc

- serde/src/de/impls.rs
- test_suite/tests/test_de.rs
> Deserialize unsized Arc and Rc

- serde_derive_internals/src/case.rs
- test_suite/tests/test_macros.rs
Hey! Thanks for the nice library =)
Here is a small patch for support of `SCREAMING-KEBAB-CASE`, that is used in some APIs. Name is inspired by already existing `SCREAMING_SNAKE_CASE` and `kebab-case`.
> SCREAMING-KEBAB-CASE support

- serde_derive/src/de.rs
- test_suite/tests/test_identifier.rs
> Fix identifier deserialization from non-u32

- serde_derive/src/de.rs
- test_suite/tests/test_macros.rs
> Fix trivial numeric cast in visit_u64

- README.md
> Clarify the README example for local builds

- serde_test/src/assert.rs
- serde_test/src/configure.rs
- serde_test/src/de.rs
- serde_test/src/lib.rs
- serde_test/src/ser.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_identifier.rs
- test_suite/tests/test_remote.rs
- test_suite/tests/test_roundtrip.rs
- test_suite/tests/test_ser.rs
Implements (roughly) https://github.com/serde-rs/serde/issues/1065#issuecomment-336735150
Fixes #1065
> Add an API for making tests for readable/compact representations

- serde_test/src/ser.rs
Before
```
expected Token::Str but serialized as Str(“F9168C5E-CEB2-4FAA-B6BF-329BF39FA1E4")
```
After
```
expected Token::Str(“f9168c5e-ceb2-4faa-b6bf-329bf39fa1e4”) but serialized as Str(“F9168C5E-CEB2-4FAA-B6BF-329BF39FA1E4")
```
> Print the contents of the expected token when a serialize assert fails

- serde_test/src/assert.rs
- serde_test/src/de.rs
- serde_test/src/token.rs
- test_suite/tests/test_annotations.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_macros.rs
> Catch wrong field names length in serde_test

- serde_derive/src/de.rs
- test_suite/tests/test_gen.rs
> Fix missing absolute paths in deserialize_seq

- serde_derive/src/de.rs
- serde_derive/src/ser.rs
- serde_derive_internals/Cargo.toml
- serde_derive_internals/src/attr.rs
- serde_derive_internals/src/lib.rs
- test_suite/Cargo.toml
- travis.sh
> Hygiene fixes

- serde_derive/src/de.rs
- serde_derive/src/lib.rs
- serde_derive/src/ser.rs
- serde_derive/src/try.rs
> More efficient try!() alternative

- serde_derive/Cargo.toml
Fixes: https://github.com/serde-rs/serde/issues/1230
> derive: bump min version of quote to 0.5.2

- .travis.yml
- travis.sh
> Add a CI build on 1.15.0

- serde_derive/src/de.rs
- serde_derive/src/lib.rs
- serde_derive/src/pretend.rs
- serde_derive/src/ser.rs
- test_suite/tests/test_gen.rs
- test_suite/tests/test_remote.rs
> Pretend remote derives are not dead code

- serde/src/de/impls.rs
- serde/src/lib.rs
- serde/src/ser/impls.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
Fixes #186.
Unfortunately the Deserialize impls only apply to `T: Sized` -- https://github.com/rust-lang/rust/issues/50513.
> Add impls for Weak

- serde_derive/src/de.rs
- test_suite/tests/compile-fail/precondition/deserialize_dst.rs
> Detect deserialize on a struct ending in dynamically sized slice

- serde/src/de/impls.rs
- serde/src/de/mod.rs
- serde/src/private/de.rs
- serde/src/private/ser.rs
- test_suite/tests/test_annotations.rs
> Support flattened untagged Options in struct fields

- serde_test/Cargo.toml
> Specify serde version required by serde_test

- serde/build.rs
- serde/src/de/impls.rs
> Stabilize Deserialize for Box<CStr>

- serde/build.rs
- serde/src/de/impls.rs
> Stabilize impls for dynamically sized Rc / Arc

- serde/src/de/value.rs
- test_suite/tests/test_value.rs
> Implement IntoDeserializer for i128 and u128

- serde/src/de/value.rs
- test_suite/tests/test_value.rs
> Implement Copy for value deserializers of primitive types

- serde/src/ser/impls.rs
- test_suite/tests/test_ser.rs
> Use try_borrow for serializing RefCell

- serde/src/private/de.rs
- test_suite/tests/test_annotations.rs
Before this change, flattening anything after a flattened map was nonsensical because the later flattened field would always observe no input fields.
```rust
struct S {
#[serde(flatten)]
map: Map<K, V>,
#[serde(flatten)]
other: Other, // always empty
}
```
This change makes a flattened map not consume any of the input fields, leaving them available to later flattened fields in the same struct. The new behavior is useful when two flattened fields that both use deserialize_map care about disjoint subsets of the fields in the input.
```rust
struct S {
// Looks at fields with a "player1_" prefix.
#[serde(flatten, with = "prefix_player1")]
player1: Player,
// Looks at fields with a "player2_" prefix.
#[serde(flatten, with = "prefix_player2")] …
```
> Allow multiple flattened maps to see the same fields

- serde/build.rs
- serde/src/de/impls.rs
- serde/src/lib.rs
- serde/src/ser/impls.rs
> Support Duration in no-std mode on new compilers

- serde/src/ser/impls.rs
- test_suite/tests/test_ser.rs
> Implement Serialize for core::fmt::Arguments

- serde/src/lib.rs
> Update path to alloc::collections for nightly-2018-07-07

- test_suite/tests/run-pass/untagged-and-borrow.rs
https://github.com/serde-rs/serde/issues/930
> test borrowing untagged enum

- .travis.yml
- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
- test_suite/tests/test_value.rs
- travis.sh
> Add Emscripten build in Travis

- serde_derive/Cargo.toml
- serde_derive/src/internals/attr.rs
- serde_derive/src/lib.rs
- serde_derive_internals/Cargo.toml
Tracking issue: https://github.com/dtolnay/syn/issues/476
> Update to syn 0.15

- serde/src/private/de.rs
- test_suite/tests/test_annotations.rs
> Fix panic deserializing flattened any after flattened struct

- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
- test_suite/tests/test_value.rs
- travis.sh
> Run test suite on asmjs

- serde/src/de/impls.rs
Before, `Vec::deserialize_in_place` would preserve the allocation of the Vec but not allocations within any of the elements. Now it preserves both.
> Optimize Vec::deserialize_in_place to deserialize elements in place

- serde_derive/src/internals/ast.rs
- serde_derive/src/internals/attr.rs
- serde_derive/src/internals/case.rs
Support Container attributes rename_all only for Serialize or Deserialize
> Support Container attributes rename_all only for Serialize or Deserialize

- README.md
> Replace serde_derive with features = ["derive"] in readme

- serde_derive/src/ser.rs
- test_suite/tests/test_macros.rs
Fix for #1468. This also overhauls my initial implementation a bit to make it a bit cleaner an easier to read.
> Fixed #1468, flattened struct fields made structs ignore their tag

- serde/src/private/de.rs
- test_suite/tests/test_macros.rs
> Allow integer key in untagged flattened map

- serde/src/de/ignored_any.rs
- test_suite/tests/test_de.rs
- test_suite/tests/test_ignored_any.rs
> Accept enums in IgnoredAny

- serde_derive/src/de.rs
- test_suite/tests/test_gen.rs
> Fix indexing bug when `skip` and `other` are combined

- README.md
> Update 'Getting help' section

- serde/src/private/ser.rs
> Forward serialize_entry on flattened maps

- serde/src/lib.rs
Add FlexBuffers to serde ecosystem list
> Add FlexBuffers to serde ecosystem list

- serde/src/private/de.rs
- serde/src/private/ser.rs
- test_suite/tests/test_annotations.rs
> Support flattening a Unit

- serde/src/de/mod.rs
- serde/src/lib.rs
- serde/src/ser/mod.rs
Mirror of https://github.com/serde-rs/serde-rs.github.io/pull/118.
> Rename TyOverby/bincode to servo/bincode

- serde/src/de/impls.rs
Only refactors, doesn't actually expose this visitor
> refactor: Merge multiple FromStr visitors to a single FromStrVisitor

- serde_derive/src/internals/attr.rs
- test_suite/tests/test_gen.rs
> Collect lifetimes inside macro invocations

- serde_derive/src/lib.rs
- serde_derive/src/ser.rs
- test_suite/tests/test_gen.rs
> Support `Self` inside fields that use serialize_with

- serde/src/de/mod.rs
- serde_derive/src/internals/ast.rs
> fix some typos

- CONTRIBUTING.md
> Update documented test command for the serde directory

- serde/build.rs
> Enable atomic64 on riscv64 arch

- serde/src/de/impls.rs
- test_suite/tests/test_de_error.rs
> Write better Visitor for NonZero integers

- README.md
- crates-io.md
> Add discord invite links

- .github/workflows/ci.yml
- serde_derive/Cargo.toml
- serde_derive/src/bound.rs
- serde_derive/src/internals/attr.rs
- serde_derive/src/internals/receiver.rs
- serde_derive/src/lib.rs
- serde_derive_internals/Cargo.toml
https://github.com/dtolnay/syn/releases/tag/1.0.90
> Update exhaustive matching to syn 1.0.90

- serde_derive/build.rs
- serde_derive/src/dummy.rs
- serde_derive/src/pretend.rs
Similar to https://github.com/serde-rs/serde/commit/55a7cedd737278a9d75a2efd038c6f38b8c38bd6, but for serde_derive.
> Invert build.rs cfgs in serde_derive

- serde/src/ser/impls.rs
- test_suite/tests/test_ser.rs
Motivated by https://stackoverflow.com/q/73806798/7884305.
> Serialize unsized `RefCell`, `Mutex` and `RwLock`

- serde/src/de/mod.rs
Same as it is on https://serde.rs/impl-deserialize.html
> Fix "deserialize" -> "deserialize_any" in Deserializer documentation

- serde_derive/src/internals/attr.rs
When this `parse_lit_str` got written in Jan 10, 2018 (https://github.com/serde-rs/serde/commit/3d64df6e87429f001e42eb62630e67ef5318b3b0), `syn::LitStr` did not expose any equivalent functionality. The same thing was added to syn later in https://github.com/dtolnay/syn/commit/d53ac2b150046116cc7971d7055319feda7418c0.
> Replace serde_derive_internal's parse_lit_str with syn::LitStr::parse

- .github/workflows/ci.yml
- serde_derive/Cargo.toml
- serde_derive/src/bound.rs
- serde_derive/src/de.rs
- serde_derive/src/internals/attr.rs
- serde_derive/src/internals/receiver.rs
- serde_derive_internals/Cargo.toml
- test_suite/tests/ui/malformed/cut_off.stderr
- test_suite/tests/ui/malformed/not_list.stderr
- test_suite/tests/ui/unexpected-literal/container.stderr
- test_suite/tests/ui/unexpected-literal/field.stderr
- test_suite/tests/ui/unexpected-literal/variant.stderr
https://github.com/dtolnay/syn/releases/tag/2.0.0
> Update to syn 2

- serde_derive/src/internals/attr.rs
- test_suite/tests/ui/malformed/trailing_expr.stderr
- test_suite/tests/ui/unexpected-literal/container.stderr
- test_suite/tests/ui/unexpected-literal/field.stderr
- test_suite/tests/ui/unexpected-literal/variant.stderr
This is designed to be more amenable to unquoted values inside attributes -- #368.
Supersedes #1704.
> Rewrite attribute parser using parse_nested_meta

- serde_derive/Cargo.toml
- serde_derive/src/internals/attr.rs
- serde_derive_internals/Cargo.toml
- test_suite/tests/ui/malformed/str_suffix.rs
- test_suite/tests/ui/malformed/str_suffix.stderr
> Reject suffixed string literals inside serde attrs

- serde_derive/src/internals/attr.rs
- test_suite/tests/ui/default-attribute/enum.stderr
- test_suite/tests/ui/default-attribute/enum_path.stderr
- test_suite/tests/ui/default-attribute/nameless_struct_fields_path.stderr
- test_suite/tests/ui/enum-representation/untagged-struct.stderr
- test_suite/tests/ui/struct-representation/internally-tagged-tuple.stderr
- test_suite/tests/ui/struct-representation/internally-tagged-unit.stderr
Follow-up to https://github.com/serde-rs/serde/pull/1695#discussion_r1275423042.
There are a few more in line 770 and below, but there it wasn't quite as clear what to set the span to.
> Update error span for attribute / data kind mismatches

- .github/workflows/ci.yml
- serde/src/de/mod.rs
> Fix `serde::de::StdError` in no-std unstable build

- precompiled/build.sh
> fix shebang in build.sh

- serde/Cargo.toml
> Reword PR 2588 comment

- serde_derive/src/internals/check.rs
- test_suite/tests/test_macros.rs
Fixes https://github.com/serde-rs/serde/issues/2643
> Allow internal tag field in untagged variant

- serde/src/de/impls.rs
> Fix more RangeFrom / RangeEnd mixups

- test_suite/tests/test_de.rs
- test_suite/tests/test_ser.rs
> Add RangeFrom and RangeTo tests

- serde/src/de/mod.rs
- serde/src/lib.rs
- test_suite/tests/test_de_error.rs
See https://github.com/serde-rs/serde/pull/2679.
> Format Unexpected::Float with decimal point

- serde/src/de/impls.rs
- serde/src/lib.rs
- serde/src/ser/impls.rs
> Document tuple impls as fake variadic

- serde_derive/src/de.rs
As mentioned in https://github.com/serde-rs/serde/pull/2842: "Maybe a struct instead of a tuple would be more suitable"
> Collect field ident and aliases into a struct

- serde_derive/src/internals/check.rs
Follow up to https://github.com/serde-rs/serde/pull/2562
> pacify clippy

- test_suite/no_std/src/main.rs
Closes https://github.com/serde-rs/serde/issues/2870.
> Replace #[start] with extern fn main

- serde_core/README.md
- serde_core/src/lib.rs
> Illustrate build timings in serde_core readme
