serde-rs/serde

serde2/src/json/ser.rs
Write "{" instead of "{{". Same for the counterpart.
=> Fix the json object delimiters

serde2/src/json/de.rs
Vim (and, I suspect, other editors as well) automatically adds a newline at the end of text files. This caused the JSON parser to fail due to trailing characters.
=> Make the JSON parser accept trailing whitespace

serde2/serde2_macros/src/lib.rs
When annotated with #[serde(default)], a field gets a default value using
std:default::Default, and will not error when decoding if the field is missing
from the input.
Addresses #9
=> Add serde default attribute for fields

serde2/serde2_macros/src/lib.rs
When compiling a module with a struct containing a derive_deserialize 
annotation, the compiler was complaining "Use of undeclared type or module
`de`".
=> Fix plugin use of de::SeqVisitor

serde_macros/src/field.rs
Prevents unused attribute warnings in code that marks fields with field
level #[serde] attributes.
=> Mark serde field attributes as used

serde_macros/src/de.rs, serde_macros/src/ser.rs
Otherwise it was possible for the expanded macro to pickup a
user-defined `Result` type, which didn't fulfill the required type
bounds and cause compilation failure.
=> fix(macros): fully qualified usage of `Result`

src/bytes.rs
As @BurntSushi observes, there is an `impl<T, U> Into<U> for T where U: From<T>`
in libcore. We have `From<Vec<u8>>` for `ByteBuf` since we have implemented
`From<T> for ByteBuf where T: Into<Vec<u8>>`, so this is redundant anyway.
=> Remove `impl Into<Vec<u8>> for ByteBuf` since it causes a compile error

Cargo.toml, src/lib.rs
The attribute allows cross-crate rustdoc links.
=> Add doc link to Cargo.toml and doc attr

serde_macros/src/de.rs, serde_macros/src/field.rs, serde_macros/src/ser.rs, tests/test_annotations.rs
Adds the rename_ser and rename_de field attributes to specify serialisation
and deserialisation specific renames.
Addresses #61
=> Add serialize, deserialize specific rename

src/iterator.rs, src/json/de.rs, src/lib.rs, tests/test_json.rs
I thought that most deserializers could make use of this
this is technically a breaking change, since it also changes the way line/col positions are reported.
1. before the `\n` was character at col pos 1, but the first line's first char was the first char of the document.
2. on eof the col-counter is not increased anymore
both can be observed by the changes in the test suite
=> separate out the line/column counting from character iteration

src/json/ser.rs
This unfortunately loses the simd-ish whitespace printer, but since pretty printing shouldn't be on a hot path, this shouldn't really matter.
Partially addresses #65.
@Byron: how's this look?
=> Allow the pretty printer character to be changed

src/json/value.rs, tests/test_json.rs
The toml crate has a very cool [lookup](http://alexcrichton.com/toml-rs/toml/enum.Value.html#method.lookup) method on its `toml::Value` enum which accepts a string and yields the value at that path, if any exists. In my opinion it's much more ergonomic than using `find_path` that we inherited from rustc-serialize, compare `lookup("user.name.last")` with `find_path(&["user", "name", "last"])`.
This implementation simply splits the input on `'.'` and then feeds the result into `find_path`.
Hopefully this addition isn't too controversial. Curious to hear what you think.
=> implement lookup method for json::Value

src/de/impls.rs, src/ser/impls.rs, tests/test_de.rs, tests/test_ser.rs
Unfortunately this PR increases build times for the `serde` crate about 70%.
The implementation is similar the the tuple visitors and should be self-explanatory.
=> Add serialization/deserialization for fixed size arrays

serde_macros/src/de.rs, src/bytes.rs, src/de/impls.rs, src/de/mod.rs, src/de/value.rs
Currently working on a serialization library for a format where all strings are byte strings. Thus, I find byte string support requiring some attention.
The proposed changes are:
1. Allow to disassemble `Bytes`/`ByteBuf` into underlying representation
2. Add a nice-looking `Debug` implementation for `Bytes`/`ByteBuf`
3. Add methods to construct strings from byte strings via str::from_utf8
4. Add default `visit_byte_buf` implementation as a fallback to `visit_bytes`
5. Implement `ValueDeserializer` for `Bytes`/`ByteBuf`
6. Recognize struct field names as byte strings.
=> Improved support for byte strings

serde/src/json/de.rs, serde_tests/tests/test_json.rs
I think this should fix it, but make sure to review it. :smiley:
=> Fix #77, integer overflow when parsing JSON scientific notation number.

serde/src/de/impls.rs
This is consistent with the other visitors.  Even though they technically do not need to be public, it's handy to have it public for 1) documentation and 2) custom deserializer implementations that can pick and choose existing visitors a la carte.
=> Make BoolVisitor public so it is documented as being in existence

serde/Cargo.toml, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
This adds a new Cargo feature so that you can opt into this feature on nightly if you need it while maintaining compatibility with stable Rust.
=> Implement serialization for `NonZero` values in nightly.

serde/src/de/impls.rs
This change is needed to use the TupleVisitor to implement a VariantVisitor
=> Make the TupleVisitors public

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_json/src/de.rs, serde_json/src/ser.rs, serde_json/src/value.rs, serde_tests/benches/bench_enum.rs, serde_tests/tests/test_bytes.rs, serde_tests/tests/test_de.rs, serde_tests/tests/test_ser.rs
Some more bits inspired by #114.
This adds the expected length of tuples, tuple structs, and tuple variants to the visitors as well as adds the variant names to the `visit_enum` method. Also renames `VariantVisitor::visit_{map,seq}` to `visit_{struct,tuple}` as well as renaming `Serializer::visit_enum_{unit,map,seq}` to `visit_{unit,struct,tuple}_variant` to be consistent with the other methods.
cc @oli-obk, @tomprogrammer, @hugoduncan
=> Add enum fields and tuple length to deserialization visitor methods, renamed some more methods

serde_json/src/de.rs, serde_json/src/error.rs, serde_json/src/lib.rs, serde_json/src/ser.rs, serde_tests/tests/test_json.rs
This patch switches json to parse a large number as a `f64` if it grows bigger than one that can fit into `i64`.
Along the way it also adds a `json::Result` helper type as well.
=> Update json number parsing to switch to floats if the number gets too big

README.md, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde_codegen/src/de.rs, serde_json/src/error.rs, serde_json/src/value.rs, serde_tests/benches/bench_enum.rs, serde_tests/benches/bench_map.rs, serde_tests/benches/bench_struct.rs, serde_tests/benches/bench_vec.rs, serde_tests/tests/test_bytes.rs, serde_tests/tests/test_de.rs
=> Remove "_error" from de::Error methods, add string argument to Error::syntax()

serde_json/src/value.rs
the default impl from the trait deserializes from a single element tuple. This caused a confusing bug in my code where deserialization failed when deserializing from `Value`, but worked if i turned the `Value` into a string in-between.
=> json deser from Value adjusted to be equal to deser from strings

serde_codegen/src/de.rs
If that is not the case, the generated code might attempt to use a
custom `Result` type with incompatible type parameters.
=> Use fully qualified `Result` type

serde/src/de/mod.rs
Have Deserializer::visit_{usize,u8,...,isize,i8,...,f32} call visit_{……u64,i64,f64}
This cuts down the amount of overloading needed by a format like toml which wants to prevent casting a float to an integer and vice versa.
=> Have deserializer numeric visits chain

serde_json/src/error.rs, serde_json/src/ser.rs, serde_tests/benches/bench_log.rs, serde_tests/tests/test_json.rs
Closes #122. This is a breaking change since it modifies the return type of serde_json::to_vec{,pretty}, so it'll require a major version bump of serde_json.
This also black boxes the json log benchmarks, which unfortunately cuts `bench_log::bench_deserializer` from about 120MB/s to 85MB/s :/
=> Reject serializing maps to JSON with non-string keys

serde/src/de/mod.rs
Resolves warnings introduced in RFC 1214.
=> Add a Sized requirement to the Deserialize trait.

serde/src/lib.rs
The lack of detailed explanations on the starting page in the docs was noted at https://users.rust-lang.org/t/lets-talk-about-ecosystem-documentation/2791/25
=> add link to the README from the docs

README.md, serde/src/ser/mod.rs, serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_codegen/src/field.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_annotations.rs
This adds two new macro annotations that will skip serializing a field if `$value.is_empty()` or `$value.is_none()` is `true`.
=> Add skip serializing fields if empty or none

README.md
Looks like someone accidentally removed the \`\`\` from the end of a code block, causing the `Serialization without Macros` section to be formatted like code
=> Fix code block end marker

serde_codegen/src/ser.rs
bug was introduced by c4392ff256c1eea6595daea987c44c084f299c11
=> $value_expr starting with a & took address of resulting bool

serde/Cargo.toml
`num` pulls in deps for features that `serde` doesn't need, so opt-out of them.
=> Opt-out of `num`s `default-features`

serde/src/de/mod.rs, serde/src/de/value.rs
There are two changes in this PR:
When using a ValueDeserializer errors produced with the methods
type_mismatch, length_mismatch and syntax were not forwarded
correctly. These methods now store all information in the enum
de::value::Error.
In constrast to https://github.com/serde-rs/serde/pull/165 this PR makes it obsolete to add the `From<de::value::Error>` trait bound to the `de::Error` trait. Even the conversion of `de::value::Error` to the deserializer specific error is not needed with this PR, the ValueDeserializer is monomorphized to use the deserializer's error type.
An example for using a `ValueDeserializer` to forward deserializing to
another type's visitor:
```rust
fn visit_u8<E>(&mut self, value: u8) -> Result<Self::Value, E>
where E: de::Error
{ …
```
=> Improve error forwarding and `ValueDeserializer` usability – Take 2

serde/src/bytes.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_tests/benches/bench_enum.rs, serde_tests/benches/bench_map.rs, serde_tests/benches/bench_struct.rs, serde_tests/benches/bench_vec.rs, serde_tests/tests/test_bytes.rs, serde_tests/tests/token.rs
serde-json PR @ https://github.com/serde-rs/json/pull/13
=> fix(#151): renaming Deserializer::visit_* to Deserializer::deserialize_*

README.md
This PR replaces the low res PNG Travis CI build status badge with it's high res SVG counterpart.
=> Use SVG version of Travis CI build status badge

serde_codegen/src/de.rs
Getting this out of the way in front of a bigger patch it would have gotten lost in. This change should do nothing. I think the intention here was to say, "Yes, take the default format if needed in renames", but this default is about data defaulting (and rename defaults are always taken anyway if needed).
=> Remove extraneous flag

serde/src/de/mod.rs, serde_codegen/src/de.rs
Formats that do not provide type hints in the serialized format (bincode, redis) rely on hinting in the deserializer. Struct key hinting was not previously supported. This was not an issue in the past because
bincode serializes structs as a keyless sequence of values. However, redis data is stored (key, value, key, value, ...), and the keys must be deserialized to properly create a struct.
The default implementation of `visit_struct_key` is simply `visit` since that was the previous method called in codegen.
I think this should be backwards compatible with 0.6.x, but you guys would know best. I am happy to resubmit against 0.7 if needed.
=> feat(de): Support struct key hinting

serde/src/de/impls.rs, serde/src/de/mod.rs
IgnoredAny was calling `deserializer.deserialize` directly which is guaranteed to Error for certain formats like redis and bincode. This adds a `deserialize_ignored_any` method to hint to such implementations.
This is not relevant for 0.6 line since ignoring is only supported on 0.7.
=> feat(de): Support hinting for IgnoredAny

serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_tests/tests/test_bytes.rs, serde_tests/tests/test_ser.rs, serde_tests/tests/token.rs
The only way to safely serialize a `Path` is to use `.to_string_lossy()`, which replaces invalid UTF-8 characters with the U+FFFD replacement character. Unfortunately this would lose information, so for our default implementations, it'd be better to punt and report an error, and leave it up to the user to decide if they want to use the lossy encoding.
Unfortunately, we had no way for `Serializer`s to require some methods on `Serializer::Error`, so there was no way before this patch for the `Path` implementation to generically report that it cannot encode this value. This adds that implementation.
breaking-change
Closes #57.
=> feat(ser): Add ser::Error trait; avoid panic when serializing Paths

serde/src/de/impls.rs
It looks like PathBuf always serializes as a string, so why not skip the indirection?
The motivation for this is [this bug](https://github.com/TyOverby/bincode/issues/53) in bincode.
=> Use deserializer.deserialize_string for PathBuf

serde_macros/Cargo.toml, serde_macros/benches/bench.rs, serde_macros/src/lib.rs
I noticed when building `serde_macros` that it was pulling in `clippy` as required. It seems like this should be an optional dependency here too, like in the other serde crates.
Also, I noticed setting the version such as `clippy = "^0.0.37"` will require updates as clippy/nightly break. If desired, I can submit another PR to change the clippy dependency to `clippy = "^0.0"` to allow all future `0.0.*` clippy versions (I can do this across all the serde crates). This way you won't have to change the `Cargo.toml` when another clippy version is released.
Let me know. Thanks!
=> fix(clippy): make clippy optional

serde/src/de/mod.rs, serde/src/ser/mod.rs, serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_annotations.rs, serde_tests/tests/token.rs
This effectively reverts #69, and restores the functionality added in #62. This feature that allows format-specific renames has never been used, and it's complicating the implementation of #207.
According to #61, if one uses serde to serialize requests that pass url-encoded parameters to a server, it might get responses back with a different capitalization scheme. This patch restores the behavior implemented in #62.
This closes #211.
=> Remove support for format-specific renames, replace with ser or de specific renames

serde_codegen/src/lib.rs
Was previously nightly. This resulted in compilation error when the clippy feature was not enabled because the clippy crate could not be found.
=> plugin(clippy) now relies on feature = "clippy"

serde/Cargo.toml, serde/src/lib.rs, serde/src/ser/mod.rs
517c2f79b70 renamed the `nightly` feature to `nightly-testing` to
reflect that the `clippy` dependency is only required when testing.
However, the code also uses `#[cfg(feature = "nightly")]` to enable
trait impls for feature-gated types. This commit restores that
functionality and fixes a few `cfg_attr`s that refer to clippy lints.
=> Fix cargo `nightly` feature

README.md, serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_annotations.rs, serde_tests/tests/test_de.rs, serde_tests/tests/test_macros.rs, serde_tests/tests/test_ser.rs, serde_tests/tests/token.rs
This is an alternative implementation of #214, #198, #208 and implements #90 and #216. This allows one to write:
```rust
struct Struct {
#[serde(default="123")]
a: i32,
#[serde(skip_serializing_if="self.b == 123")]
b: i32,
#[serde(serialize_with="(self.b == 123).serialize(serializer)"]
c: i32,
#[serde(deserialize_with="Ok(if try!(bool::deserialize(deserializer) { 123) } else { 0 })"]
d: i32,
}
```
cc @oli-obk, @target-san, @arcnmx
=> Add codegen expr magic for default, skip serializing, and alternative serializers

README.md
Just opening this PR for discussion.
I noticed that [serde-rs/yaml](https://github.com/serde-rs/yaml/) seems pretty dead. The missing pieces are a YAML emitter (partially implemented) and parser (not started).
I found a reasonably complete YAML emitter and parser at [yaml-rust](https://crates.io/crates/yaml-rust) so I threw together [a serde that uses it](https://github.com/dtolnay/serde-yaml).
Is this something that would be valuable to contribute to serde-rs so that YAML is supported despite being theoretically slower than possible? Later we can swap in our own emitter and parser as the pieces materialize.
=> YAML serde based on yaml-rust

serde_codegen/src/ser.rs, serde_tests/tests/test_macros.rs
Deriving Serialize or Deserialize on Void-like enums triggered an unused_variables warning.
=> Silence unused_variables warning with empty enums

serde_codegen/src/attr.rs
Result<T, E> aliases usually provide one or both of `T` and `E`. This
would cause an error when using deserialize_with:
error: wrong number of type arguments: expected 1, found 2
which unhelpfully just pointed to `#[derive(Deserialize)]`
=> Fix `deserialize_with` in module with Result alias

README.md
=> Add missing close brackets in readme

serde_codegen/src/attr.rs, serde_tests/tests/test_annotations.rs
I don't think we should ever access the rust-name directly
needed to port serde-xml to 0.7
=> pass the renamed `deserialize` field name to missing_field

serde_codegen/src/attr.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_annotations.rs
Addresses part of #197.
The generated code for a struct like:
struct Test<A, B, C> {
a: X<A>,
#[serde(skip_serializing)]
b: B,
#[serde(serialize_with="...")]
c: C,
}
Used to be:
impl<A, B, C> Serialize for Test<A, B, C>
where A: Serialize,
B: Serialize,
C: Serialize,
{ ... }
Now it is:
impl<A, B, C> Serialize for Test<A, B, C>
where X<A>: Serialize,
{ ... }
Both `skip_serializing` and `serialize_with` mean the type does not need to implement `Serialize`.
The remaining work for #197 is to add a `skip_deserializing` attribute that does the equivalent for `Deserialize` (also filed as #259), and to infer `T: Default` appropriately.
=> feat(codegen): Inhibit generic bounds if skip_serializing

README.md, serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_tests/tests/test_de.rs
Addresses part of #197.
This will be more exciting when I add logic to omit the `T: Deserialize` bound for fields that have `skip_deserializing`, like what #260 does for `skip_serializing`, but I am waiting for a code review on #260 before implementing that.
=> feat(codegen) skip_deserializing

serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_tests/tests/test_annotations.rs
This addresses the bug pointed out by @erickt in https://github.com/serde-rs/serde/pull/265#issuecomment-209016467.
=> fix(codegen): Take into account default=... when skip_deserializing

serde/src/de/impls.rs, serde_tests/tests/test_de.rs, serde_tests/tests/test_ser.rs
+tests for serializing Box<[T]>, which already worked. Addresses #287.
=> fix(impls): Deserialize impl for Box<[T]>

serde_codegen/src/attr.rs, serde_codegen/src/bound.rs, serde_codegen/src/de.rs, serde_codegen/src/lib.rs.in, serde_codegen/src/ser.rs, serde_tests/tests/test_annotations.rs
This PR addresses the remaining part of #197 (following up on my previous PRs #260 and #265) by inferring a `T: Default` bound for fields that (1) have `#[serde(default)]`, or (2) have `#[serde(skip_deserializing)]` and not `#[serde(default=...)]`. I factored out the generics-building code from #260 to share it between ser and de.
This PR also makes progress toward #259, although I have not attempted to resolve the `MapVisitor::missing_field` problem mentioned in that issue.
I would like to add more tests before merging, but the implementation is ready for review.
=> feat(codegen): Infer Default and Deserialize bounds correctly

README.md, serde_codegen/src/attr.rs, serde_codegen/src/bound.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_tests/tests/test.rs, serde_tests/tests/test_annotations.rs, serde_tests/tests/test_bytes.rs, serde_tests/tests/test_de.rs, serde_tests/tests/token.rs
Addresses #159.
The generated code looks like:
```rust
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _IMPL_DESERIALIZE_FOR_MyStruct: () = {
extern crate serde as _serde;
#[automatically_derived]
impl _serde::de::Deserialize for MyStruct {
// ...
}
};
```
=> fix(codegen): Support `extern crate serde` not in toplevel module

serde/Cargo.toml, serde_codegen/Cargo.toml, serde_codegen/src/attr.rs, serde_codegen/src/bound.rs, serde_macros/Cargo.toml, serde_tests/Cargo.toml
This one is mostly about updating dependencies on syntex, aster, and quasi -- along with a small code patch for adapting to the actual interface changes.
=> Update for latest libsyntax changes

README.md
The field type `T` does not have to be a generic type parameter of the serialize_with or deserialize_with function.
=> Clarify serialize_with and deserialize_with documentation

serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_tests/tests/test.rs.in, serde_tests/tests/test_de.rs, serde_tests/tests/test_gen.rs
Addresses both #305 and #307.
To fix #305, this PR adds turbofish to SeqVisitor and MapVisitor calls where type inference can fail due to https://github.com/rust-lang/rust/issues/33449.
To fix #307, this PR adds a PhantomData in the deserialize_with implementation as explained in that ticket.
I did both in one PR because they touch the same code.
=> Reduce dependence on type inference

serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs
Addresses #312. We already do this almost everywhere.
=> Prefix type parameters and lifetimes with double underscore

serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_tests/tests/test_annotations.rs
Addresses #259.
The solution is, if a field is missing:
- If there is a default expression, use the default expression (this includes `skip_deserializing`).
- If the field has deserialize_with, fail with `Visitor::Error::missing_field(name)`.
- Otherwise call `visitor.missing_field(name)` to possibly handle the field.
This means `deserialize_with` no longer goes through the visitor's `missing_field`, instead failing directly unless there is a default. Thus fields with `deserialize_with` do not require Deserialize as a bound. The missing field behavior can be controlled by setting a default for the field.
=> Field with deserialize_with should not implement Deserialize

serde/src/de/mod.rs, serde_codegen/src/de.rs, serde_tests/tests/test_de.rs, serde_tests/tests/token.rs
Addresses #59. Let me know whether you think we need an escape hatch to opt out of this check.
=> feat(codegen): Detect repeated struct field when deserializing

serde_codegen/Cargo.toml
serde_codegen has syntex 0.32 under dependencies, but syntex 0.31 under build-dependencies...
=> Do not depend on multiple syntex versions

serde_codegen/src/attr.rs, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_gen.rs
Fixes #330 and a number of related bugs around (de)serialize_with in newtype structs, tuple structs, newtype variants, and tuple variants.
The most interesting thing in this PR is a significantly condensed version of `wrap_serialize_with`. It now works a lot more like `wrap_deserialize_with`, with just a thin wrapper that provides a `serialize` method. Please confirm that the contortions in the original implementation were not necessary. I had to make this change to support serialize_with in newtype structs and newtype variants.
=> Support (de)serialize_with in tuples

README.md, serde_codegen/src/attr.rs, serde_codegen/src/bound.rs, serde_codegen/src/de.rs, serde_codegen/src/lib.rs, serde_codegen/src/ser.rs, serde_tests/tests/test_gen.rs
Addresses (2) and (3) in https://github.com/serde-rs/serde/issues/336#issuecomment-220378916.
- If there is a `#[serde(bound="...")]` attribute on the type, use the union of that and the actual type's `where` clause as the `where` clause for the impl and do not attempt to generate any additional `where` clauses whatsoever.
- If there is a `#[serde(bound="...")]` attribute on a field, use that and do not attempt to generate any additional `where` clauses for the field.
The `bound` attribute behaves similar to `rename` in that you can specify a single attribute that applies to both ser and de, or individual ones.
```
#[serde(bound="D: Serialize + Deserialize")]
#[serde(bound(serialize="D: Serialize", deserialize="D: Deserialize"))]
```
EDIT: now addresses (4) from …
=> Attribute for handwritten where clauses

README.md, examples/.cargo/config, examples/serde-syntex-example/build.rs, serde_codegen/src/lib.rs
Required for #358. We can remove `serde_codegen::register` in the next breaking release.
This allows Syntex users to avoid being broken by Serde bumping its Syntex dependency.
=> Add serde_codegen::expand to avoid public Syntex dependency

serde_macros/tests/compile-fail/duplicate_attributes.rs_, serde_macros/tests/compile-fail/str_ref_deser.rs
I tried adding cfail tests to `serde_tests`, but mixing syntex-`serde_codegen` and `serde_macros` doesn't end well. We can't use `serde_codegen` as-is for testing without building our own test harness out of asserting that `expand` runs successful. Luckily there are already compile-fail tests in `serde_macros`. Let's simply continue adding them there.
fixes #341
=> more cfail tests

serde_codegen/Cargo.toml, serde_codegen/src/bound.rs, serde_codegen/src/de.rs, serde_codegen/src/lib.rs, serde_codegen/src/lib.rs.in, serde_codegen/src/ser.rs, serde_item/Cargo.toml, serde_item/src/attr.rs, serde_item/src/error.rs, serde_item/src/lib.rs
Fixes #396. @KodrAus [let me know whether this fits the bill.](https://github.com/dtolnay/serde/tree/5c6a0e12e95974e3c131386e8e0528b6b9cfa6fa/serde_item/src)
a few other changes to make the API a little more presentable:
- Rename attr::{ContainerAttrs,VariantAttrs,FieldAttrs} to remove the "Attrs" (I see you worked on the corresponding [clippy lint](https://github.com/Manishearth/rust-clippy/issues/904)).
- Rename attr::Container* to attr::Item to correspond with item::Item and ast::Item. The others already had a correspondence (attr::Variant/item::Variant/ast::Variant, attr::Field/item::Field/ast::Field). Also a unit struct isn't much of a "container."
- Change item::Item::from_ast to return a meaningful error enum instead of printing a message that was hard to generalize to other uses. …
=> Factor attr parsing into serde_item crate

serde_codegen/src/de.rs, testing/tests/test_annotations.rs
Fixes https://github.com/serde-rs/json/issues/96.
=> Invalid-length when enum seq is too short

serde_codegen/src/de.rs
I am working on JSON parser performance. One huge improvement (30-40%) is making the `peek()` function as cheap as possible and doing pessimistic error handling such that line/column is only computed if an error happens.
For context: the `while` loop exits when `peek()` returns a closing brace `}`. `$extract_values` checks for any missing keys. `visitor.end()` consumes the closing brace.
The current `peek()` updates the iterator position so currently "missing field" errors correctly point to the closing brace. The faster `peek()` does not update position. In order for "missing field" errors to point to the closing brace instead of the previous character, we need to consume the closing brace before checking for missing keys.
=> Close the map before checking for missing fields

serde/src/de/mod.rs
=> impl Display for de::Type

.cargo/config, examples/.cargo/config, serde_codegen/Cargo.toml, serde_macros/Cargo.toml, serde_test/Cargo.toml, testing/Cargo.toml
This makes it possible to use `cargo clone` + `cargo build`.
=> Use cargo override instead of relative paths

serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_codegen/src/ser.rs, serde_test/src/de.rs, serde_test/src/ser.rs, serde_test/src/token.rs, testing/tests/test_annotations.rs, testing/tests/test_bytes.rs, testing/tests/test_de.rs, testing/tests/test_macros.rs, testing/tests/test_ser.rs
I took the liberty of also simplifying some of serde codegen (mainly the parts where we do a lot of effort to create types that are going to get optimized out). I think all that was necessary to fit the visitor pattern. The new system as imagined by @dpc is much easier to implement, although it requires additional helper objects
fixes #386
cc @dpc
=> Revamp Map/Seq serialization

serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs
=> add more extensive docs

serde_codegen/src/bound.rs, testing/tests/test_gen.rs
Fixes #435 and fixes #436 and fixes #441 and fixes #443.
=> Generate bounds on type parameters only

testing/tests/test_gen.rs
This will be required for testing PhantomData once it works.
```rust
struct S<T> {
phantom: PhantomData<T>
}
assert::<S<X>>();
```
=> Add tests for concrete instantiations in test_gen

README.md
This is no longer necessary as of #456. Closes #427.
*This reverts commit 93968455f3f4158e4c455b1b6743fe3571c74e8a.*
=> Revert "Mention Empty Bounds for Recursion in Readme"

serde/src/ser/mod.rs
Just a minor documentation fix for grammar and and a copy/paste error.
=> Fix typos in docstring of ser::Error.

serde/src/de/mod.rs
This makes the generated rustdoc easier to read.
=> Remove underscore from parameter names in deserializer traits

serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_test/src/ser.rs, testing/tests/test_bytes.rs
Like what's been done on the deserialization side with MapVisitor, this
allows some weirder uses of Serde to handle the key and value in
separate steps.
r? @dtolnay
=> Split serialize_map_elt

serde_codegen/Cargo.toml, serde_macros/Cargo.toml, serde_test/Cargo.toml
@azerupi @oli-obk @erickt do you think this would fix the problem in #470? Are there other problems it could cause?
When compiling an old serde_macros this prevents it from depending on a new serde_codegen which may be on an incompatible quasi version.
=> Use exact dependencies on other serde crates

.travis.yml
Fixes #461. This is a little more flexible because we can push out documentation improvements before a release if necessary. We will need to manually bump the "docs" branch as part of the release process.
=> Generate docs from 'docs' branch instead of master

serde_codegen/src/de.rs, serde_codegen/src/ser.rs
We were using ast::Expr surrounded by `{ }` in a few places that should have been ast::Block. This PR decreases the indentation to make the generated code easier to read when it needs to be debugged.
=> Remove unnecessary nesting from generated impls

serde_codegen/src/de.rs
Neither `__FieldVisitor` nor `__Visitor` need the `__D: Deserializer` type parameter.
=> Simplify generated visitors

.cargo/config, serde_codegen/Cargo.toml, serde_codegen/build.rs, serde_macros/Cargo.toml, serde_test/Cargo.toml
=> use a thread in the build script of serde_codegen to allow env vars to control the stack size

serde/src/lib.rs
The URL does not need to contain the crate name. With this URL rustdoc can generate correct external doc links.
=> Adjust doc(html_root_url)

serde_codegen/src/ser.rs
I don't think this negatively affects maintainability of the code in serde_codegen and I think there is some value in keeping our generated code relatively clear so that people can use it as a template when implementing Serialize manually with minor modifications.
=> Remove `if !false { ... }` from generated serialization code

serde/src/bytes.rs
This commit adds `Bytes::new(&[u8])` and `ByteBuf::from<T: Into<Vec<u8>>>(T)`.
Fixes #519.
=> Add constructors for Bytes and ByteBuf

serde_codegen/src/ser.rs, testing/tests/test_gen.rs
=> Fix "variable does not need to be mutable" warning

serde_codegen/src/ser.rs, testing/tests/test_gen.rs
Without this:
```
error[E0244]: wrong number of type arguments
--> src/api/accounts.rs:19:10
|
19 | #[derive(Serialize, Deserialize, Debug)]
|          ^^^^^^^^^^ expected 1 type arguments, found 2
```
=> Result needs to be fully qualified

serde_codegen/Cargo.toml
#558 was failing because it bumped aster without bumping quasi, and quasi continued to pull in the old aster. cc @erickt
=> Bump quasi and aster

serde_codegen/src/de.rs, serde_codegen/src/ser.rs
Fixes #562. In #548 I wanted to preserve byte-for-byte identical code to what we had before, which required some workarounds. This cleans up those workarounds.
=> Clean up syn workarounds

serde/src/de/impls.rs, serde/src/ser/impls.rs
Also use the same strategy for serialization as for deserialization of
`IpAddr`.
Fixes #551.
=> Allow the use of `IpAddr` implementations on stable

serde_codegen/src/lib.rs
Fixes #590 and probably fixes #574.
Spans in the AST returned by `parse_item_from_source_str` and other parsing
functions contain byte offsets into the source code they were parsed from. The
pretty printer uses these Spans [here][1] to preserve the representation of
literals when parsing and printing back out unmodified.
In this bug, the byte offset of a string in the input to
`parse_item_from_source_str` coincidentally matched the byte offset of a totally
different string in the input to `parse_crate_from_file` called [here][2] by
Syntex. The Span from the former triggered the pretty printer to write out the
content of the latter.
By using the same ParseSess, Spans from the two `parse_*` calls never collide.
[1]: https://github.com/rust-lang/rust/blob/1.12.0/src/libsyntax/print/pprust.rs# …
=> Not safe to share Spans from one ParseSess to another

serde_codegen/src/de.rs
Makes the code generated by `derive(Deserialize)` compile cleanly when `unused_results` lint is enabled.
I'm not familiar with the internals at all, so it's entirely possible that there are more spots that trip the lint up, this is just something that starts shouting at you pretty much immediately, with trivial code:
```
#![feature(proc_macro)]
#![warn(unused_results)]
#[macro_use]
extern crate serde_derive;
pub struct Foo {
pub foo: i32,
#[serde(skip_deserializing)]
pub bar: i32,
}
```
With 0.8.15 you get:
```
warning: unused result
--> src\lib.rs:7:1
|
7 | #[derive(Deserialize)]
| ^^^^^^^^^^^^^^^^^^^^^^
|
note: lint level defined here
--> src\lib.rs:2:9
|
2 | #![warn(unused_results)]
|         ^^^^^^^^^^^^^^
= note: this error originates in a macro outside of the …
```
=> Explictly discard result of visiting IgnoredAny

serde_codegen/Cargo.toml, serde_codegen/src/lib.rs, serde_derive/Cargo.toml, serde_derive/src/lib.rs
This is blocked on https://github.com/rust-lang/rust/issues/37788.
I removed `serde_codegen::expand_single_item` because (1) nothing on GitHub calls it and (2) there is basically no correct way to use it anymore with the latest nightly.
=> Ask proc_macro_derive to ignore serde attributes

serde_codegen/src/de.rs, serde_codegen_internals/src/attr.rs, testing/tests/test_de.rs
This partially fixes https://github.com/serde-rs/serde/issues/638
I guess this patch is too naive, there are probably some case I missed. I'd like to get some feedback on this.
=> Implemented skip_deserializing for enum

serde/src/de/mod.rs, serde_test/src/de.rs
Fixes #657. This is a breaking change but only breaks buggy code.
=> Remove the Deserialize trait bound on Visitor::Value

serde/src/lib.rs
Fixes #669.
This dates back about 2 years to 3fac47e01cbb10c2b6c519f354e9ce1f3792e567, when `serde::de::Error` was the only Error and `serde::ser::Error` did not exist.
Now `serde::Error` is just confusing.
=> Stop exporting serde::de::Error as serde::Error

serde_codegen/src/de.rs, testing/tests/test_gen.rs
Fixes #676 and adds tests for #677.
=> Handle various degenerate cases

serde/src/ser/impls.rs, serde/src/ser/mod.rs
When I left the comment in the issue I noticed that the code wasn't as general as it could be. Alternatively the `IntoIterator` could be forwarded all the way into the `Serialize` function, as to not call `into_iter` before it is needed. Any preferences?
=> make `ser::iterator` more general by taking `IntoIterator`

serde_codegen/src/de.rs, serde_test/src/de.rs
fixes #559 
writing tests for this is hard, because we never have a string available, just a generic `K: Deserialize`, we could create a custom Deserializer that allows exactly one string deserialization and it has to match a given string. It's somewhat roundabout, but that's the best I can think of.
=> fix various serde(rename) bugs

serde_codegen/src/de.rs, testing/tests/test_de.rs
Fixes #444.
Previously, skipped fields were included in the __Field enum. Now they are not, so the variants of the __Field enum may be non-consecutive like __field0, __field2 if the second field is skipped. Skipped fields will error with Error::unknown_field if using deny_unknown_fields and will go through the usual __Field::__ignore variant otherwise.
=> Treat skipped fields as unknown

serde/src/bytes.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/macros.rs, serde_codegen/src/de.rs, serde_test/src/de.rs, testing/tests/test_annotations.rs, testing/tests/test_gen.rs
This ensures Deserialize::deserialize calls Deserializer::deserialize_\* at most once.
Half of #651.
=> Enforce correct use of Deserialize trait

serde/src/de/mod.rs
This fixes a 2-5% performance regression in deserialization due to the DeserializeSeed change. https://github.com/serde-rs/serde/issues/650#issuecomment-273939785
=> Inline <PhantomData<T> as DeserializeSeed>::deserialize

serde_codegen/src/de.rs, testing/tests/test_annotations.rs
This is the drive-by fix from #701.
=> Filter the slice of expected field and variant names

serde/Cargo.toml, serde/src/bytes.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/error.rs, serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_codegen/Cargo.toml, serde_codegen/src/de.rs, serde_codegen/src/ser.rs, serde_derive/Cargo.toml, serde_test/Cargo.toml, serde_test/src/de.rs, serde_test/src/error.rs, testing/Cargo.toml, testing/tests/test_annotations.rs, testing/tests/test_de.rs, testing/tests/test_ser.rs
Fixes #528 and fixes #675 and fixes #709 and fixes #702..
Essentially we rely on every Visitor to tell us what type of data it is expecting. See the doc comments in serde/src/de/mod.rs.
In general my goal is to centralize error message building in Serde rather than leaving it to each individual format to reimplement lousy messages. This is a step in that direction and I have a design for https://github.com/serde-rs/json/issues/173 which I will implement in another PR.
=> Errors redesign

serde_codegen/src/de.rs, testing/tests/test_de.rs
I removed this in #671 but it is still used by Bincode [here](https://github.com/TyOverby/bincode/blob/54205283375e6a3d79e6506225f8e15a7cab7520/src/serde/reader.rs#L519-L520).
=> Restore visit_usize and visit_bytes for identifying variants

.travis.yml, Cargo.toml, test_suite/deps/Cargo.toml, travis.sh
This lets me run `./travis.sh` locally and it completes all of the builds against all of the trains in 2 minutes 25 seconds on my machine, which is faster than waiting for Travis.
=> Allow running travis build locally

serde/src/export.rs, serde/src/lib.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
=> Use absolute paths to Ok, Err, and other types and methods

serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
In the most recent nightly this gives a strongly worded warning:
> **warning:** use of deprecated item: long since replaced
=> Remove the EnumSet impls

serde/src/de/content.rs, serde/src/de/mod.rs, serde/src/de/private.rs, serde/src/de/value.rs, serde/src/ser/mod.rs, serde/src/ser/private.rs, serde_codegen_internals/src/attr.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, serde_test/src/de.rs, serde_test/src/lib.rs, test_suite/tests/compile-fail/enum-representation/internal-tuple-variant.rs, test_suite/tests/compile-fail/enum-representation/internally-tagged-struct.rs, test_suite/tests/compile-fail/enum-representation/untagged-and-internal.rs, test_suite/tests/compile-fail/enum-representation/untagged-struct.rs, test_suite/tests/test_de.rs, test_suite/tests/test_macros.rs
Fixes #415 and fixes https://github.com/serde-rs/json/issues/67.
The attribute for untagged enums is:
```rust
enum E {
/* variants */
}
```
During serialization, the variant is serialized as though it were not part of an enum. Struct variants are serialized as structs, tuple variants are serialized as tuples, unit variants are serialized as unit, and newtype variants are serialized as the value.
During deserialization, we buffer the content of the Deserializer and try it against each variant in order, returning the first one that deserializes successfully from that content.
The attribute for internally tagged enums is:
```rust
#[serde(tag = "type")]
enum E {
/* variants */
}
```
The enum must contain …
=> Untagged and internally tagged enums

serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs
These are two convenience functions to serialize iterators.
=> Introduce collect_seq and collect_map

serde/Cargo.toml
Pending https://github.com/integer32llc/rust-playground/issues/82.
=> Playground feature to get serde_derive picked up by integer32 playground

serde_codegen_internals/src/attr.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_macros.rs
I've been working on #758 but got stuck partway through the implementation, so I'm uploading what I've got for the moment. **Do not pull this, it's a work in progress and won't build anyway.**
See the comments in `serialize_internally_content_tagged_variant` for where I'm stuck. The basic issue is that I want to take a enum tuple variant like:
```
#[serde(tag = "t", content = "c")]
enum A {
B(C, D)
}
```
And split out something like:
```
{"t": "B", "c": ["value_of_C", "value_of_D"]}
```
I know how to spit out the `"t": "B"` via `serialize_field`, and the interior of `["value_of_C", "value_of_D"]` via serialize_tuple_variant`. But I can't figure out a way to spit out a `"c":` to prefix the internal content with, because it seems that all the methods for serializing fields expect to do the …
=> WIP: Initial work on supporting #758

serde_codegen_internals/src/attr.rs, serde_derive/src/de.rs, test_suite/tests/compile-fail/default-attribute/enum.rs, test_suite/tests/compile-fail/default-attribute/nameless_struct_fields.rs, test_suite/tests/test_de.rs
This allows structs to use the default value for each field defined in
the struct’s `std::default::Default` implementation, rather then the
default value for the field’s type.
```
struct StructDefault {
a: i32,
b: String,
}
impl Default for StructDefault {
fn default() -> StructDefault {
StructDefault{
a: 100,
b: "default".to_string(),
}
}
}
```
The code above will now return `100` for field `a` and `”default”` for
`b`, rather then `0` and `””` respectively.
=> Add support for `#[serde(default)]` on structs

serde/src/de/content.rs
These commits are to fix #775 for internally tagged enums. My testcases pass with this implementation but I'm not sure about the code correctness. Is there a particular test file I should add to?
Untagged enums need a similar fix.
=> Fix internally tagged enums by implementing ContentDeserializer::deserialize_enum

serde/src/ser/mod.rs
`SerializeTuple` supports `serialize_element`, not `serialize_field`.
=> Fix documentation of serialize_tuple and SerializeTuple

serde/src/de/impls.rs, serde/src/ser/impls.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
From #800: `serde` currently ships with an `impl` of `Serialize` and `Deserialize` for [`str`](https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L80) and [`String`](https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L90), but not for the null-terminated C-like string types [`ffi::CStr`](https://doc.rust-lang.org/std/ffi/struct.CStr.html) and [`ffi::CString`](https://doc.rust-lang.org/std/ffi/struct.CString.html). Under the hood, these string implementations are very similar, and providing serialization implementations for the latter two shouldn't be too hard.
This patch adds serialization and deserialization of those types through null-terminated `[u8]`s. I'm guessing I should also implement tests for this, but didn't find where those should go. …
=> impls for null-terminated FFI string types

serde/src/de/value.rs, test_suite/tests/test_value.rs
In serde_derive the visitors we generate for unit variants are able to deserialize from u32, so this should be supported for u32's value deserializer as well.
=> Implement deserialize_enum for U32Deserializer

serde/src/de/impls.rs, serde/src/lib.rs, test_suite/Cargo.toml, test_suite/tests/compiletest.rs, test_suite/tests/test_de.rs, test_suite/tests/test_gen.rs, test_suite/tests/test_ser.rs, travis.sh
Fixes #810.
I've scoped the `impl` under `feature="unstable"` for now (don't know what the policy for that feature is), but this should possibly not be merged until https://github.com/rust-lang/rust/issues/40380 lands and fully stabilizes [`CString::into_boxed_c_str`](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.into_boxed_c_str). At that point, `feature="unstable"` should obviously be removed.
=> Add Deserialize impl for CStr

serde/src/export.rs, serde/src/lib.rs, serde_codegen_internals/src/attr.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/compile-fail/type-attribute/type_attribute_fail_from.rs, test_suite/tests/compile-fail/type-attribute/type_attribute_fail_into.rs, test_suite/tests/test_annotations.rs
I have implemented `#[serde(types(from="type", into="type", from_as="type", into_as="type))]` to allow more complicated serialization and deserialization. The `from` type specifies the type from which the result will be converted after being passed through `Derializer`. The `into` type specifies the type that the value will be converted to before being passed through `Serializer`. `from_as` and `into_as` provide an additional safe cast as necessary between the `Serializer`/`Deserializer` and the `From`/`Into` traits.
=> Macro attributes to specify From and Into trait types for structs and enums

serde/Cargo.toml, serde/src/lib.rs
Fixes #797. @oli-obk I am still not settled on whether this should be on or off by default but I am leaning toward off.
=> Re-export derives from serde

appveyor.yml, serde/src/de/impls.rs, serde/src/ser/impls.rs, test_suite/no_std/src/main.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs, travis.sh
This commit implements the two serde traits for the libstd `OsStr` and
`OsString` types. This came up as a use case during implementing sccache where
we're basically just doing IPC to communicate paths around. Additionally the
`Path` and `PathBuf` implementations have been updated to delegate to the os
string ones.
These types are platform-specific, however, so the serialization/deserialization
isn't trivial. Currently this "fakes" a newtype variant for Unix/Windows to
prevent cross-platform serialization/deserialization. This means if you're doing
IPC within the same OS (e.g. Windows to Windows) then serialization should be
infallible. If you're doing IPC across platforms (e.g.  Unix to Windows) then
using `OsString` is guaranteed to fail as bytes from one OS won't deserialize on
the …
=> Implement Serialize/Deserialize for OsStr/OsString

serde/Cargo.toml
This is required for #826 as both are updated to Deserialize<'de> together.
=> Use the live serde_derive for serde doc tests

serde/Cargo.toml, serde/src/bytes.rs, serde/src/de/content.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/private.rs, serde/src/de/value.rs, serde/src/macros.rs, serde_derive/src/bound.rs, serde_derive/src/de.rs, serde_test/src/assert.rs, serde_test/src/de.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_gen.rs
This is the boring part of #492 - just plumbing `'de` through all the relevant places.
In this PR all `#[derive(Deserialize)]` generated implementations will apply to any lifetime `'de`. The remaining work for #492 is to support a `#[serde(borrow)]` attribute that constrains the lifetimes that `'de` is allowed to be.
---
The weirdest part of this PR is in serde/src/macros.rs where it assumes that the lifetime of your deserializer is called `'de`. So in particular this would not work:
```rust
impl<'x> Deserializer<'x> for MyDeserializer {
/* ... */
forward_to_deserialize! {
/* ... */
}
}
```
I think settling on a particular lifetime name as a convention is fine and we can add a feature to `forward_to_deserialize!` to select a different lifetime name in the future if necessary.
---
There is …
=> Add a 'de lifetime to the deserialize traits

serde/src/de/impls.rs, serde/src/utils.rs, test_suite/tests/test_de.rs
Fixes #836.
Type | No longer deserialized from
--- | ---
() | empty seq
bool | "true" and "false" strings
number | FromStr
string | unit
various sequence types | unit
[T; 0] | unit
various map types | unit
These conversions are bad because they make untagged enums confusing.
```rust
#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_json;
#[derive(Deserialize, Debug)]
enum E {
B(bool),
S(String),
}
fn main() {
// This should be E::S but is actually E::B because of implicit conversion.
println!("{:?}", serde_json::from_str::<E>("\"false\"").unwrap());
}
```
It looks like bool from string and number from string were added only to support XML in https://github.com/serde-rs/serde/pull/70. @RReverser can you make serde-xml-rs work without those …
=> Remove questionable type conversions

serde/src/de/impls.rs, test_suite/tests/test_de.rs
These are currently broken anyway... deserializing 10000.0f64 as u8 successfully gives you 16u8 even though integer-to-integer conversions check for out of bounds.
=> Remove implicit conversion from float to integer

serde/src/private/ser.rs, serde_codegen_internals/src/ast.rs, serde_codegen_internals/src/attr.rs, serde_codegen_internals/src/check.rs, serde_codegen_internals/src/lib.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/compile-fail/remote/bad_getter.rs, test_suite/tests/compile-fail/remote/bad_remote.rs, test_suite/tests/compile-fail/remote/enum_getter.rs, test_suite/tests/compile-fail/remote/missing_field.rs, test_suite/tests/compile-fail/remote/nonremote_getter.rs, test_suite/tests/compile-fail/remote/unknown_field.rs, test_suite/tests/compile-fail/remote/wrong_de.rs, test_suite/tests/compile-fail/remote/wrong_getter.rs, test_suite/tests/compile-fail/remote/wrong_ser.rs, test_suite/tests/test_remote.rs
Fixes #496.
For types with public fields, all you need to provide is a definition of the type.
```rust
#[serde(remote = "time::Duration")]
struct DurationDef {
secs: u64,
nanos: u32,
}
```
For structs with one or more private fields, also provide getters for the private fields and a conversion to the remote type.
```rust
#[serde(remote = "time::Duration")]
struct DurationDef {
#[serde(getter = "time::Duration::as_secs")]
secs: u64,
#[serde(getter = "time::Duration::subsec_nanos")]
nanos: u32,
}
impl From<DurationDef> for time::Duration {
fn from(def: DurationDef) -> time::Duration {
time::Duration::new(def.secs, def.nanos)
}
}
```
Then these definitions can be used to serialize and deserialize the remote type.
```rust …
```
=> Derive for remote types

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/macros.rs, serde/src/private/de.rs, serde/src/private/macros.rs, serde/src/private/ser.rs, serde/src/ser/mod.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, serde_test/src/de.rs, serde_test/src/ser.rs
- Rename `deserialize_struct_field` to `deserialize_identifier` to indicate that it is used not just for struct fields but also for enum discriminants.
- Use u32 as the type of variant indices in the serializer API to match the way that our generated visitors expect visit_u32.
Fixes #722.
=> Standardize on u32 for struct field index and enum variant index

serde/src/macros.rs
Fixes #852.
```rust
forward_to_deserialize! {
<W: Visitor<'q>>
bool u8 u16 u32 u64 i8 i16 i32 i64 f32 f64 char str string unit option
seq seq_fixed_size bytes byte_buf map unit_struct newtype_struct
tuple_struct struct struct_field tuple enum ignored_any
}
```
This is a breaking change for Deserializer implementations where the type already has a `V` type parameter.
=> Configurable forward_to_deserialize

serde/Cargo.toml, serde/src/de/impls.rs, serde/src/ser/impls.rs, travis.sh
=> Put rc impls behind a cfg

serde/src/de/from_primitive.rs, serde/src/de/ignored_any.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/utf8.rs, serde/src/de/value.rs, serde/src/export.rs, serde/src/lib.rs, serde/src/private/de.rs, serde/src/private/ser.rs, serde/src/ser/impls.rs, serde/src/ser/impossible.rs, serde/src/ser/mod.rs
This sort of thing was getting out of hand:
```rust
#[cfg(feature = "std")]
use std::borrow::Cow;
#[cfg(all(feature = "collections", not(feature = "std")))]
use collections::borrow::Cow;
#[cfg(all(feature = "collections", not(feature = "std")))]
use collections::{BinaryHeap, BTreeMap, BTreeSet, LinkedList, VecDeque, Vec, String};
#[cfg(feature = "std")]
use std::collections::{HashMap, HashSet, BinaryHeap, BTreeMap, BTreeSet, LinkedList, VecDeque};
#[cfg(feature = "collections")]
use collections::borrow::ToOwned;
#[cfg(any(feature = "std", feature = "collections"))]
use core::cmp;
use core::fmt;
#[cfg(feature = "std")]
use core::hash::{Hash, BuildHasher};
use core::marker::PhantomData;
#[cfg(feature = "std")]
use std::net;
#[cfg(feature = "std")]
use std::path;
use core::str;
#[cfg(feature …
```
=> Centralize all import wrangling

serde/Cargo.toml, serde/src/de/impls.rs, serde/src/lib.rs
https://github.com/rust-lang/rust/pull/41437
Backport of https://github.com/serde-rs/serde/pull/898 to 0.9.x
=> Remove usage of unstable core::num::Zero, which was removed upstream.

serde_derive_internals/src/ast.rs, serde_derive_internals/src/attr.rs
The deprecated `syn::MacroInput` is still used in some places in `serde_derive`. It looks like commit c52e131 didn't fully update all instances to `syn::DeriveInput`.
This fixes it.
=> Replace deprecated MacroInput; completes c52e131

serde/src/private/de.rs, serde_derive/src/de.rs, test_suite/tests/test_macros.rs
Implementation includes happy-path test; wasn't sure where to put the test for `deny_unknown_fields`, but was able to verify that locally in another crate.
#816
=> Fix #816 - adjacently-tagged enums honor deny_unknown_fields

serde/src/private/de.rs, test_suite/tests/test_macros.rs
=> Fix internally tagged struct variant containing unit variant containing borrowed string

serde_derive/src/de.rs, test_suite/tests/test_de.rs
serde-cbor supports a "packed" serialization flag which causes keys to
be serialized as their indices, but the deserializer currently has to
hardcode support for this format. We can simply support deserialization
of struct keys from integers as we already do for enum variants.
=> Support deserialization of struct keys from integers

serde/Cargo.toml, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/export.rs, serde/src/lib.rs, serde/src/private/de.rs, serde/src/private/ser.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, travis.sh
This PR removes the unstable `collections` feature to align with https://github.com/rust-lang/rust/pull/42648. Removing the feature is a breaking change but the feature is unstable and anyone using it is already broken on the most recent nightly.
No impls were harmed in the making of this PR.
Fixes #955.
=> Merge crate `collections` into `alloc`

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
=> Fix deserializer bounds on remote derive

serde/src/de/impls.rs
Backported commit from the derive_seed branch which removes a bit of boiler plate (which helps when porting this module to the seeded variants)
=> refactor: Implement Deserialize of wrapper types with a macro

test_suite/tests/test_ser.rs
Windows's `SystemTime` do not have nanosecond resolution which caused the test duration to be truncated https://github.com/rust-lang/rust/blob/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/libstd/sys/windows/time.rs#L177
=> Fix SystemTime serialization test on Windows

Cargo.toml, test_suite/no_std/Cargo.toml, travis.sh
=> Workaround for "no bin target named serde_derive_tests_no_std"

serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
For remote derive this will give the derived methods the same visibility as the definition.
```rust
#[serde(remote = "...")]
struct Def; // Def::serialize and deserialize are private to this module
#[serde(remote = "...")]
pub struct Def; // Def::serialize and deserialize are public
#[serde(remote = "...")]
pub(crate) struct Def; // Def::serialize and deserialize are pub(crate)
```
Fixes #1000. @arcnmx
=> Inherit the visibility of remote struct definition

serde/src/ser/mod.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_de.rs
=> Inform serializers about skipped fields.

serde_derive/src/bound.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, serde_derive_internals/src/attr.rs, serde_derive_internals/src/check.rs, test_suite/tests/compile-fail/with-variant/skip_de_newtype_field.rs, test_suite/tests/compile-fail/with-variant/skip_de_struct_field.rs, test_suite/tests/compile-fail/with-variant/skip_de_tuple_field.rs, test_suite/tests/compile-fail/with-variant/skip_de_whole_variant.rs, test_suite/tests/compile-fail/with-variant/skip_ser_newtype_field.rs, test_suite/tests/compile-fail/with-variant/skip_ser_newtype_field_if.rs, test_suite/tests/compile-fail/with-variant/skip_ser_struct_field.rs, test_suite/tests/compile-fail/with-variant/skip_ser_struct_field_if.rs, test_suite/tests/compile-fail/with-variant/skip_ser_tuple_field.rs, test_suite/tests/compile-fail/with-variant/skip_ser_tuple_field_if.rs, test_suite/tests/compile-fail/with-variant/skip_ser_whole_variant.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_gen.rs
Work in progress for #1013. So far I've implemented the `serialize_with` half. Any early feedback would be appreciated.
=> implement (de)serialize_with for variants

serde_derive/src/bound.rs, serde_derive/src/de.rs, test_suite/tests/test_gen.rs
For a struct containing a &'static field, this will generate:
```rust
impl Deserialize<'static>
```
instead of:
```rust
impl<'de: 'static> Deserialize<'de>
```
Fixes #975.
=> Special case for 'static fields

serde/src/private/de.rs, serde_derive/src/de.rs, test_suite/tests/test_macros.rs
During serialization, internally tagged enums invoke the Serializer's serialize_struct. In JSON this turns into a map which uses visit_map when deserialized. But some formats employ visit_seq when deserializing a struct. One example is rmp-serde. Such formats were previously unable to deserialize an internally tagged enum. This change fixes it by adding visit_seq for internally tagged enums.
Fixes https://github.com/3Hren/msgpack-rust/issues/130.
=> Support deserializing internally tagged enum from seq

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_test/src/assert.rs, serde_test/src/de.rs, serde_test/src/lib.rs, serde_test/src/ser.rs, test_suite/tests/macros/mod.rs, test_suite/tests/test_de.rs, test_suite/tests/test_roundtrip.rs, test_suite/tests/test_ser.rs
This implements the KISS suggested in https://github.com/serde-rs/serde/issues/790.
It is possible that one of the other approaches may be better but this
seemed like the simplest one to reignite som discussion.
Personally I find the original suggestion of adding two traits perhaps slightly
cleaner in theory but I think it ends up more complicated in the end
since the added traits also need to be duplicated to to the `Seed`
traits.
Example usage in https://github.com/rust-lang-nursery/uuid: https://github.com/Marwes/uuid/commit/f908fd3ec7a564b79dab99dc2a519a698b7f9d7d
Closes #790
=> Serialize to binary if the serde format is not human readable

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
=> Ignore skipped fields when looking for borrowed lifetimes

serde_derive_internals/src/ast.rs, serde_derive_internals/src/attr.rs, test_suite/tests/compile-fail/borrow/duplicate_variant.rs, test_suite/tests/compile-fail/borrow/struct_variant.rs, test_suite/tests/test_gen.rs
```rust
enum RelData<'a> {
#[serde(borrow)]
Single(RelObject<'a>),
#[serde(borrow)]
Many(Vec<RelObject<'a>>),
}
```
Fixes #929.
=> Allow borrow attribute on newtype variants

serde_derive/src/bound.rs, test_suite/tests/test_gen.rs
=> Fix bounds for macro named the same as a type parameter

serde_test/Cargo.toml
This is due to implementing is_human_readable which was added in serde 1.0.16.
=> serde_test requires serde 1.0.16 to work

serde/src/private/de.rs, serde/src/private/ser.rs, test_suite/tests/test_macros.rs
Fixes https://github.com/serde-rs/json/issues/379.
```rust
struct Info;
#[serde(tag = "topic")]
enum Message {
Info(Info),
}
```
This should serialize and deserialize as `{"topic":"Info"}` even though ordinarily unit structs are not allowed to deserialize from an empty map.
=> Allow internally tagged newtype variant containing unit struct

serde/src/private/de.rs
Inlining `cautious` helps LLVM figure out what is going on with array deserialization.  I figured we might as well do the others while we're here.
=> Inline various deserialization helper methods.

serde_derive/src/de.rs, serde_derive_internals/src/ast.rs, serde_derive_internals/src/attr.rs, test_suite/tests/test_de.rs
When a field should be skipped during deserialization, it will not use its own Default implementation
when the container structure has `#[serde(default)]` set.
=> Solved #1105.

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/private/de.rs, serde_derive/Cargo.toml, serde_derive/src/de.rs, serde_derive/src/fragment.rs, serde_derive_internals/src/attr.rs, serde_test/Cargo.toml, serde_test/src/assert.rs, test_suite/Cargo.toml, test_suite/tests/test_de.rs
The actual deserialize work is WIP, because I probably need to refactor it so it can be feature-flagged off. I think the first two commits are "good to go", though.
One thing missing from this design is deriving deserialize_from for exactly C-like enums, but that can obviously be done later.
Pushing this up now because my brain is melting trying to do the non-C-like enum work I need for webrender, and so I'm gonna take a bit of a "break" by dealing with review complaints.
=> Add and derive deserialize_from

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/private/de.rs, serde_derive/Cargo.toml, serde_derive/src/de.rs, serde_test/src/assert.rs, test_suite/Cargo.toml
Fixes #1122. @Gankro @nox @oli-obk I am basically prepared to release this. Any objections?
I believe `deserialize_in_place`, even to the extent that it conflicts with [placement-in](https://github.com/rust-lang/rust/issues/27779) and [`std::ops::InPlace`](https://doc.rust-lang.org/std/ops/trait.InPlace.html), has all the right connotations for this API. People recognize placement as a way to avoid copies and leverage existing allocations.
```rust
vec.push(create_element());
let x = T::deserialize(de)?;
vec.place_back() <- create_element();
T::deserialize_in_place(de, &mut x)?;
```
Tellingly, @Gankro even used the phrase ["in place"](https://github.com/serde-rs/serde/commit/bc221abb04ed942afed87a41147802f1c7d3955a#diff-222404300d4750d007f9d729af3ec439R559) when describing the …
=> Rename deserialize_from to deserialize_in_place

appveyor.yml
Fixes https://github.com/serde-rs/serde/issues/862 by ducking the issue. (Cribbed from `rust-openssl`)
=> get rustup-init with curl to avoid tls failures

serde_derive_internals/src/check.rs, test_suite/tests/compile-fail/conflict/adjacent-tag.rs, test_suite/tests/compile-fail/conflict/internal-tag.rs
Fixes https://github.com/serde-rs/serde/issues/1161.
=> Disallow variant field names to conflict with tag of internally-tagged enum

serde/src/private/de.rs
This changes the deserialize implementation for a borrowed Cow<[u8]> to specifically request a byte slice, rather than a borrowed string.
The old behavior breaks any program which relies on data being deserialized the same way as it was serialized and uses Cow<[u8]>. In serde_json, it just wouldn't deserialize. In bincode, it deserialized normally unless the bytes were invalid UTF8.
See https://github.com/TyOverby/bincode/issues/231 for error description, and test program.
I'm not sure where a test for this behavior would fit in, since it's a "what hint to provide the deserializer" failure, but if needed I can try and make one.
Thanks!
=> Fix borrowed Cow<'_, [u8]> deserializing as str.

README.md
Hi,
This PR adds some information how to use Serde in ```no_std``` because it was not obvious to me
=> [no_std] Add instructions in README.MD

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs
… gated on the `unstable` Cargo feature.
These are new standard library types. Tracking issue: https://github.com/rust-lang/rust/issues/49137
=> impl Serialize and Deserialize for std::num::NonZero*

serde_derive_internals/src/attr.rs, test_suite/tests/test_gen.rs
The following has worked since `remote` was introduced. It generates `fn serialize` and `fn deserialize` with the same signature as `Serialize::serialize` and `Deserialize::deserialize`.
```rust
#[serde(remote = "RemoteSelf")]
struct RemoteSelf;
```
This PR makes the following equivalent to the above. This did not work before due to our use of the `remote` path in places where `Self` had not the right meaning.
```rust
#[serde(remote = "Self")]
struct RemoteSelf;
```
=> Special case remote = "Self"

serde_derive/src/bound.rs, serde_derive/src/de.rs, serde_derive/src/lib.rs, serde_derive/src/ser.rs, serde_derive_internals/src/attr.rs
Quote's default is def_site but it appears call_site is likely to stabilize before def_site. Thus we try to use only call_site.
```rust
macro_rules! quote {
($($tt:tt)*) => {
quote_spanned!($crate::proc_macro2::Span::call_site()=> $($tt)*)
}
}
```
@alexcrichton
=> Prefer call site spans

README.md
Fixes #1173.
<a href="https://blog.rust-lang.org/2016/11/10/Rust-1.13.html"><img src="https://img.shields.io/badge/rustc-1.13+-bc71d0.svg" alt="Rustc Version 1.13+" width="300"></img></a>
=> Rustc version badge

serde_derive_internals/src/ast.rs, serde_derive_internals/src/check.rs, test_suite/tests/compile-fail/conflict/flatten-within-enum.rs
This adds an error message for the currently unsupported use of flatten within a struct variant.
Fixes #1185
=> Produce error message for use of flatten within struct variant

serde_derive_internals/src/check.rs, test_suite/tests/compile-fail/conflict/flatten-newtype-struct.rs, test_suite/tests/compile-fail/conflict/flatten-tuple-struct.rs
This adds a missing error message for unsupported flattening on tuple structs.  Fixes #1188
=> Produce error message for use of flatten in tuple structs

serde_derive/src/bound.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
Prior to this, structs and enums that had fields using associated types wouldn't have the appropriate where bounds set. This fixes that, meaning that this now builds:
```rust
trait Trait {
type Assoc;
}
#[derive(Serialize)]
struct Struct<T: Trait> {
assoc: T::Assoc,
}
```
Fixes #1208.
=> Support #[derive(Serialize, Deserialize)] when using associated types

serde_derive/src/ser.rs
The existing implementation was unnecessarily complicated.
```rust
struct __AdjacentlyTagged<'__a> {
data: (&'__a String,),
phantom: _serde::export::PhantomData<AdjacentlyTagged>,
}
impl<'__a> _serde::Serialize for __AdjacentlyTagged<'__a> {
fn serialize<__S>(
&self,
__serializer: __S,
) -> _serde::export::Result<__S::Ok, __S::Error>
where
__S: _serde::Serializer,
{
let (__field0,) = self.data;
_serde::Serialize::serialize(__field0, __serializer)
}
}
_serde::ser::SerializeStruct::serialize_field(
&mut __struct,
"content",
&__AdjacentlyTagged {
data: (__field0,),
phantom: _serde::export::PhantomData::<AdjacentlyTagged>,
},
)?;
```
Instead the new implementation does simply:
```rust
_serde::ser::SerializeStruct::serialize_field(
&mut __struct,
"content",
__field0,
)?;
```
Fixes #1224.
=> Improve Serialize of adjacently tagged newtype variants

serde_derive/src/de.rs
This eliminates 110 instantiations of Result::map in Xi and reduces binary size by 229 kilobytes.
Fixes #1225.
=> Reduce instantiations of Result::map in Deserialize of unit variants

serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/private/de.rs
This eliminates 12% of the Serde-related code in the Xi release binary as measured by:
```bash
nm -S target/release/xi-core \
| awk '/serde/{sum += strtonum("0x"$2)} END{print sum}'
```
=> Mark error construction as cold code

serde/src/de/mod.rs, serde/src/private/de.rs, serde_derive/src/de.rs, test_suite/tests/test_annotations.rs
=> Support deserializing a flattened internally tagged enum

serde/Cargo.toml, serde/build.rs
Eventually we will want a build script that enables Serde impls for i128 and u128 -- https://github.com/serde-rs/serde/issues/1136. As a first step here is a build script that does nothing to see whether we can roll this out without breaking anyone's workflow, without having a supported feature at stake in the event that it needs to be rolled back.
=> Build script that does nothing

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs
Fixes #1264. The NonZero type was removed from nightly in https://github.com/rust-lang/rust/pull/50808.
=> Remove impls for NonZero<T>

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
=> Fix generated code for deserializing untagged newtype variant

serde_derive/src/de.rs, serde_derive/src/internals/ast.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, serde_derive/src/internals/mod.rs, serde_derive/src/ser.rs, test_suite/tests/compile-fail/transparent/at_most_one.rs, test_suite/tests/compile-fail/transparent/de_at_least_one.rs, test_suite/tests/compile-fail/transparent/ser_at_least_one.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_gen.rs
=> Transparent attribute to specify that representation is the same as its only field

serde/build.rs, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
… regardless of the `unstable` feature. Fix #1274.
=> Implement for std::num::NonZero* on Rust 1.28+

serde/src/de/from_primitive.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/integer128.rs, serde/src/lib.rs, serde/src/macros.rs, serde/src/private/de.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, serde_test/src/de.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
Fixes https://github.com/serde-rs/serde/issues/1136.
=> Add Serde impls for i128 and u128

serde/src/lib.rs
Hello there,
We've been working on a serde-compatible [Apache Avro](http://avro.apache.org/docs/current/) rust client library. It supports all the main Avro features, with a serde-friendly interface.
The crate is documented, tested and (slightly 🙂) benchmarked.
Crate link: https://crates.io/crates/avro-rs
Crate repository: https://github.com/flavray/avro-rs
=> Add Avro to the list of supported data formats

serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
=> Implement traits for `!`

.travis.yml, travis.sh
As suggested in #1303. Thanks!
This should prevent accidentally inserting something under one of these cfgs that is available only on a newer rustc. For example if something is changed in the Duration serialization, but that change works only on a recent rustc, our test suite will not have caught it before.
In the interest of not taking forever to build in Travis, this only does a quick `cargo build --no-default-features` and `cargo build` of the serde crate on these versions.
=> CI builders for all versions mentioned in the build script

serde_derive/src/de.rs, serde_derive/src/ser.rs
With the 2018 preview, and presumably when the edition is officially released, `extern crate` will be unidiomatic, and will generate warnings.
This suppresses the warning for the `extern crate` generated in the `Serialize` and `Deserialize` derives.
=> Suppress 'extern crate' warning for rust 2018

serde/build.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/lib.rs, serde/src/ser/impls.rs, serde/src/ser/mod.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
Copied implementation from Range, is it OK?
Edit: I will fix the failing tests but `RangeInclusive` structure was modified in [#51622](https://github.com/rust-lang/rust/pull/51622), should we wait for the next Rust release?
=> Implement Serialize and Deserialize for RangeInclusive

serde/src/lib.rs
Currently compilation fails when enabling both the `alloc` and `rc` features because of an update to `liballoc`. A previous PR (https://github.com/serde-rs/serde/issues/1335) to fix this didn't catch that `Arc` now lives under `alloc::sync`. This is a quick fix =)
=> Fix compilation under `rc` feature

travis.sh
Here's the change to `travis.sh` referred to [here](https://github.com/serde-rs/serde/pull/1359#issuecomment-414516526).
=> Update travis.sh to also test `--no-default-features --features "rc alloc"`

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs, test_suite/tests/test_unstable.rs, test_suite/tests/unstable/mod.rs
Fixes #1362.
```rust
enum r#type {
r#type {
r#type: (),
}
}
```
Serializes to: `{"type":{"type":null}}`
=> Trim the r# from raw identifiers in user-facing strings

serde/build.rs
Emscripten doesn't currently support i128 and will fail with the following error if they're used:
```
LLVM ERROR: Instruction not yet supported for integer types larger than 64 bits
```
=> Disable i128 integers on Emscripten targets

serde_derive/Cargo.toml
This bumps the minimal acceptable versions in Cargo.toml to versions that are compatible with `-Z minimal-versions`. This is part of the process of seeing how hard this is for crates to use in preparation for getting it stabilized for use in CI, specifically upstreaming the changes required to get criterion working with it. It is easy to use if all of your dependencies support it, but much harder if trying to impose it on them.
I am not sure that this is all the changes needed for all users of all the crates, but it is enough to `handlebars-rust` to work with `minimal-versions`
=> update a deb for minimal-versions

serde/src/private/de.rs, test_suite/tests/test_annotations.rs
Currently an internally tagged enum with a unit variant will fail to deserialize if the map contains unknown fields.
[Example on Playground](https://play.rust-lang.org/?gist=58c1609b0ed43cb8275ea3f1e4fa0c31&version=nightly&mode=debug&edition=2015)
This change attempts to address that by having the `InternallyTaggedUnitVisitor.visit_map` method consume the map before returning.
I've added a test case for the simple enum case and for the case where the unit enum variant is flattened into a struct.
=> Fix internally tagged enum deserialization with unknown fields

serde/src/private/de.rs
This allows `ContentDeserializer` and `ContentRefDeserializer` to deserialize unsigned integers in `deserialize_identifier`, which then allows enums inside untagged enums to be correctly decoded in formats which encode the enum variant as an integer.
Fixes https://github.com/serde-rs/serde/issues/1437. CC https://github.com/3Hren/msgpack-rust/issues/178
=> Accept integers variant encoding in Content

serde_derive/src/de.rs
This allows the following to work:
```rust
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DOM {
Text(
String,
#[serde(default, skip_serializing_if = "HashMap::is_empty")] HashMap<...>), // optional data
),
Element(...),
Comment(...),
}
```
`DOM::Text("...", HashMap::new())` becomes encoded as an adjacently tagged enum tuple variant, but because of the skip_serializing_if parameter we may omit the second field of the variant when serializing, if the condition is true. When deserializing, at the moment, serde complains that it was expecting a tuple of two types, but found 1. The new behavior after this PR is if the `default` attr was used, Default::default() (or a program-supplied method) is called to populate that value.
This survives the round trip for me with both …
=> Adds support for the default attr to tuple variants in enums.

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, serde_derive/src/ser.rs, test_suite/tests/test_macros.rs, test_suite/tests/ui/enum-representation/internally-tagged-struct.rs, test_suite/tests/ui/enum-representation/internally-tagged-struct.stderr, test_suite/tests/ui/struct-representation/internally-taged-tuple.rs, test_suite/tests/ui/struct-representation/internally-taged-tuple.stderr, test_suite/tests/ui/struct-representation/internally-tagged-unit.rs, test_suite/tests/ui/struct-representation/internally-tagged-unit.stderr
This is a patch to address #760 to allow #[serde(tag="...")] on structs. I guess, this patch would require a change in the docs, so it is still WIP.
Added test test_internally_tagged_struct.
Renamed EnumTag to TagType as it now also used for structs.
Modified serialize_struct_as_struct.
Removed ui/enum-representation/internally-tagged-struct test
=> Allow #[serde(tag="...")] on structs

serde_derive/src/ser.rs, test_suite/tests/test_macros.rs
Bug fix for #1449
Modified serialize_struct_as_struct.
Added test test_internally_tagged_braced_struct_with_zero_fields
=> Bug fix to support the tag attribute on braced structs with zero fields

serde/build.rs, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
Implemented `Serialize` and `Deserialize` traits for various interval-related types from `std`.
Could help me to setup `cfg`s etc properly?
=> Impl Serialize/Deserialize for std::ops::{Bound, RangeFrom, RangeTo, RangeToInclusive}

serde_derive/src/de.rs
This PR resolves #1491.
I also changed the .travis.yml file to properly install clippy and removed the job from the "allow_failure_ matrix. Further explanations in #1491.
If that is not welcomed, I am happy to remove the last commit again but then I am not sure how to actually test the code change to prevent regressions.
=> Don't generate code with redundant closures

serde_derive/src/de.rs, serde_derive/src/dummy.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs, test_suite/tests/test_serde_path.rs
This is intended to be used by other crates which provide their own proc
macros and use serde internally. Today there's no consistent way to put
`#[derive(Deserialize)]` on a struct that consistently works, since
crates may be using either `features = ["derive"]` or relying on
`serde_derive` separately.
Even if we assume that everyone is using `features = ["derive"]`,
without this commit, any crate which generates
`#[derive(serde::Deserialize)]` forces its consumers to put `serde` in
their `Cargo.toml`, even if they aren't otherwise using serde for
anything.
Examples of crates which suffer from this in the real world are
tower-web and swirl.
With this feature, it's expected that these crates would have `pub
extern crate serde;` in some accessible path, and add
`#[serde(serde_path = …
=> Allow `#[serde(crate = "...")]` to override `extern crate serde`

.travis.yml
The nightly compiler just added a dependency on serde in https://github.com/rust-lang/rust/pull/60053, so libserde now ends up in the sysroot, breaking crate resolution inside of compiletest. We will need to figure out how else to run these tests.
```console
error[E0464]: multiple matching crates for `serde`
--> $DIR/wrong_ser.rs:9:10
|
9 | #[derive(Serialize)]
|          ^^^^^^^^^
|
= note: candidates:
crate `serde`: /rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserde-2b75907288aa7c40.rlib
crate `serde`: /serde/test_suite/deps/target/debug/deps/libserde-33e0a319242344ce.rlib
```
=> Temporarily disable compiletest testing in CI

serde/src/de/value.rs, test_suite/tests/test_value.rs
StringDeserializer implements deserialize_enum for deserializing unit variants out of a string, so it seems reasonable for MapAccessDeserializer to implement deserialize_enum for deserializing the other kinds of variants out of a map.
https://users.rust-lang.org/t/serde-custom-deserialize-untagged-enum-with-tagged-variant/28003
=> Support deserializing enum out of MapAccessDeserializer

serde/src/export.rs, serde_derive/src/de.rs
The fact that the existing `no_std` test suite only runs on Nightly (why is it a binary crate instead of a library crate?) and that there seems to be no test suite for the alloc feature at all makes me uncertain on how to add a test for this, but I'm happy to add it after being told where / how. This is it, anyway:
```rust
#![no_std]
use serde::Deserialize;
struct Foo;
struct Bar {
#[serde(flatten)]
foo: Foo,
}
```
Without this PR, it fails with this:
```
error[E0599]: no method named `to_string` found for type `&str` in the current scope
--> src/lib.rs:8:10
|
8 | #[derive(Deserialize)]
|          ^^^^^^^^^^^
|
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps …
```
=> Fix a compile error in derive(Deserialize) with no_std + alloc

serde/src/integer128.rs
The docs imply that the only consideration for using the
serde_if_integer128 macro is support for older versions of Rust, but
Serde's build configuration for 128-bit integers is also gated on the
target platform. For example, if Serde is being compiled for an
emscripten target, then it will not provide 128-bit integer APIs.
See also: https://github.com/BurntSushi/rust-csv/issues/158
=> Update docs for serde_if_integer128

serde/Cargo.toml
Fixes #1575.
Local tests are passing and looks like the `unstable` dependency was mostly a safeguard
=> Make `alloc` feature work on stable

serde/build.rs, serde/src/de/impls.rs, serde/src/ser/impls.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
Fixes #1496.
The tests for deserialization are kind of cheesy because Atomic* types don't implement PartialEq. Let me know if you want me to try to make them better.
=> Implement serialization and deserialization for std::sync::atomic types

serde/build.rs
Fixes #1579 
I grepped through the rust target definitions. Here are the ones with at least 64-bit atomics:
```
aarch64-apple-ios
aarch64-fuchsia
aarch64-linux-android
aarch64-pc-windows-msvc
aarch64-unknown-cloudabi
aarch64-unknown-freebsd
aarch64-unknown-hermit
aarch64-unknown-linux-gnu
aarch64-unknown-linux-musl
aarch64-unknown-netbsd
aarch64-unknown-none
aarch64-unknown-openbsd
aarch64-wrs-vxworks
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
arm-wrs-vxworks
arm-wrs-vxworks-sf
armv6-unknown-freebsd
armv6-unknown-netbsd-eabihf
armv7-apple-ios
armv7-linux-androideabi
armv7-unknown-cloudabi-eabihf
armv7-unknown-freebsd
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabihf
armv7-unknown-netbsd-eabihf
armv7-wrs-vxworks …
```
=> conservatively limit atomic features

serde/src/export.rs, serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, test_suite/tests/test_annotations.rs, test_suite/tests/ui/conflict/from-try-from.rs, test_suite/tests/ui/conflict/from-try-from.stderr, test_suite/tests/ui/transparent/with_try_from.rs, test_suite/tests/ui/transparent/with_try_from.stderr, test_suite/tests/ui/type-attribute/try_from.rs, test_suite/tests/ui/type-attribute/try_from.stderr
This pull request adds a new serde attribute `try_from` which will make serde try to convert the type specified in the attribute to the type serde is trying to deserialize into. (#1524)
For example,
```rust
use serde::Deserialize;
use serde_json;
use std::convert::TryFrom;
#[derive(Deserialize, Debug)]
#[serde(try_from = "u32")]
enum Color {
Red,
}
impl TryFrom<u32> for Color {
type Error = String;
fn try_from(value: u32) -> Result<Self, Self::Error> {
if value > 10 {
Err("out of range".into())
} else {
Ok(Color::Red)
}
}
}
fn main() {
let result: Color = serde_json::from_str("2").unwrap();
println!("result = {:?}", result);
let _: Color = serde_json::from_str("100").unwrap();
}
```
will produce the following output:
```
result = Red
thread 'main' panicked at 'called `Result::unwrap()` on …
```
=> Add serde attribute `try_from`

serde/build.rs, serde/src/de/impls.rs, serde/src/ser/impls.rs
Resolves issue #1574 - now that NonZeroI* types are stabilized, it's helpful to support them.
=> Add support for NonZeroI* types

.travis.yml
```console
error: failed to parse manifest at `/home/travis/build/serde-rs/serde/test_suite/Cargo.toml`
Caused by:
editions are unstable
Caused by:
feature `edition` is required
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```
=> Work around failing to parse manifest in 1.27 and 1.28 builds

serde/src/de/mod.rs, serde/src/lib.rs, serde/src/ser/mod.rs, serde/src/std_error.rs
This PR adds `serde::ser::StdError` and `serde::de::StdError` which are either a re-export of `std::error::Error` (if "std" is enabled) or a new identical trait (otherwise).
```rust
#[cfg(feature = "std")]
pub use std::error::Error as StdError;
#[cfg(not(feature = "std"))]
pub trait StdError: Debug + Display {
fn source(&self) -> Option<&(Error + 'static)> { None }
}
```
Serde's error traits `serde::ser::Error` and `serde::de::Error` require `std::error::Error` as a supertrait, but only when Serde is built with "std" enabled. Data formats that don't care about no\_std support should generally provide their error types with a `std::error::Error` impl directly:
```rust
#[derive(Debug)]
struct MySerError {...}
impl serde::ser::Error for MySerError {...}
impl std::fmt::Display for MySerError …
```
=> Export std error type so no_std data formats don't need a "std" feature

serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
Fixes #1396 
The derive logic for newtype variants was not considering the possibility that the one value in the newtype might be skipped. This pull request fixes that. Additionally it adds some test cases that failed before, and now succeed.
=> Fix (de)serialization of new types where the internal type is skipped

serde_derive/src/ser.rs
Replace skip_seralizing tuple members with `_` in generated serializer.
I'm not totally convinced this is the right solution, since it requires creating 2x the `Vec`s, but it's the most "correct" solution I've found.
=> Fix unused variable warning when field of adjacently tagged enum is skipped

serde/build.rs, serde/src/de/impls.rs, test_suite/tests/test_de.rs
- Deserialize `PathBuf` from UTF-8 bytes, like `&Path` already does.
- Deserialize `Box<Path>` through `PathBuf`, analogous to `Box<CStr>`.
Fixes #1633
=> Improve Path deserialization

serde/Cargo.toml
This ensures that all features supported by serde are always available
through the derive macro provided through the feature flag.
Fixes: #1647
---
From discussion on https://github.com/dtolnay/trybuild/pull/37
=> serde_derive: require the same version as serde

serde/src/private/de.rs, test_suite/tests/test_de.rs, test_suite/tests/test_macros.rs
Fixes https://github.com/serde-rs/serde/issues/1668.
Note: the test suite fails to compile on my machine for some reason. I still added a test verifying the expected behavior nevertheless – could you please check if it's correct?
=> Allow untagged unit variants to deserialize from `Visitor::visit_none()`

serde/src/private/de.rs
I've written a [custom `Cow` implementation](https://github.com/maciejhirsz/beef/) that's meant to be (mostly) a drop-in replacement for `std::borrow::Cow`.
The `#[derive(Deserialize)]` macro currently does specialization for `Cow` by ident name when using `#[serde(borrow)]`, which is smart, but it also means [we get the false positives](https://github.com/serde-rs/serde/blob/078e88b2235992282c3fe72a6e7365db9508f46b/serde_derive/src/internals/attr.rs#L1704-L1725), as it is in this case:
```rust
use beef::Cow;
struct Foo<'a> {
#[serde(borrow)]
foo: Cow<'a, str>,
}
```
Will produce following compile error:
```
^^^^^^^^^^^
|
expected struct `beef::generic::Cow`, found enum `std::borrow::Cow`
in this macro invocation
```
This PR modifies …
=> Allow #[serde(borrow)] for non-std Cow

serde/src/ser/mod.rs
According to https://github.com/serde-rs/serde/pull/789#pullrequestreview-24156711 this was implemented originally using `write!(...).unwrap()` due to https://github.com/rust-lang/rust/issues/40103, but that problem was later fixed in https://github.com/rust-lang/rust/pull/40117.
=> Simplify default Serializer::collect_str implementation

serde_derive/src/dummy.rs
When creating a binary crate with a `src/main.rs` and `#[derive(Deserialize, Serialize)]`, running `cargo doc` on it will result in new doc items for generated constants:
```rust
use serde::{Deserialize, Serialize};
#[derive(Deserialize, Serialize)]
struct Dummy {
}
fn main() {
println!("Hello, world!");
}
```
This is because Cargo runs with `--document-private-items` internally for `src/main.rs`. If you put the same code in a `src/lib.rs` the private items will not be documented by default, so you won't see them there for default `cargo doc`.
The items will be visible both for `src/lib.rs` and `src/main.rs` if the `struct` itself is `pub`.
I believe the generated `_IMPL_{}_FOR_{}` constants should not be visible in rustdoc and this merge request seems to fix the issue for me.
=> Hide generated dummy const in rustdoc

serde/src/ser/impls.rs
Allow using `&mut fmt::Formatter` as a serializer for primitive types.
One use-case I have in mind in particular is implementing `Display` for enums that also implement `Serialize`.
If you believe this impl should exist, due to coherence, this crate is the only place it could exist.
=> impl Serializer for &mut fmt::Formatter

serde_derive/src/de.rs, test_suite/tests/test_macros.rs
=> Deserialize adjacently tagged newtype variants with optional content as None instead of erroring when content field is missing

.github/workflows/ci.yml
We have a gap in coverage of pre-NLL-on-2015-edition compilers (the 1.31 through 1.35 range) which resulted in CI failing to catch dda070f45cb02b26186d2579efaefd838022a26c.
=> Add a CI builder on 1.31.0

serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs
=> Add support for packed structs.

serde_derive/src/bound.rs, serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, serde_derive/src/internals/mod.rs, test_suite/tests/test_gen.rs
Fixes https://crater-reports.s3.amazonaws.com/pr-72622/master%237726070fa755f660b5da3f82f46e07d9c6866f69/reg/wirefilter-engine-0.6.1/log.txt.
=> Look inside of None-delimited groups when examining types

serde_derive/Cargo.toml, serde_derive/build.rs, serde_derive/src/dummy.rs, test_suite/tests/expand/de_enum.expanded.rs, test_suite/tests/expand/default_ty_param.expanded.rs, test_suite/tests/expand/generic_enum.expanded.rs, test_suite/tests/expand/generic_struct.expanded.rs, test_suite/tests/expand/generic_tuple_struct.expanded.rs, test_suite/tests/expand/lifetimes.expanded.rs, test_suite/tests/expand/named_map.expanded.rs, test_suite/tests/expand/named_tuple.expanded.rs, test_suite/tests/expand/named_unit.expanded.rs, test_suite/tests/expand/ser_enum.expanded.rs, test_suite/tests/expand/void.expanded.rs
Fixes #1683
The error message for the code mentioned in https://github.com/rust-lang/rust/issues/46991 is now as follows:
```text
error[E0277]: the trait bound `S: _::_serde::Serialize` is not satisfied
--> src/main.rs:14:5
|
14   |     serde_json::to_string(&S);
|                           ^^ the trait `_::_serde::Serialize` is not implemented for `S`
| 
```
=> Use underscore consts on Rust 1.37+

serde/src/lib.rs, serde/src/ser/mod.rs
This started warning in the most recent nightly (2020-06-21).
```console
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
--> serde/src/lib.rs:92:43
|
92 | #![cfg_attr(feature = "unstable", feature(specialization, never_type))]
|                                           ^^^^^^^^^^^^^^
|
= note: `#[warn(incomplete_features)]` on by default
= note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
```
Originally from https://github.com/serde-rs/serde/pull/736.
=> Remove len hint specialization

serde_derive/src/internals/attr.rs, test_suite/tests/test_macros.rs
Further improves the patches related to #1747 which worked well as long as `packed` was the first attribute in the repr annotation. Now as long as the attribute exists it will behave appropriately.
=> Improve `packed` repr matching and add tests.

serde/src/lib.rs
This library is better maintained and better documented (https://github.com/nox/serde_urlencoded/issues/43).
=> Replace serde_urlencoded link with serde_qs

serde/src/de/impls.rs
Automatically generated enum variant deserializers allowed any integer
type as the discriminant, but the hand-written ones for specific enum
types such as Result or IpAddr only allowed types up to u32. This broke
some non-human-readable deserializers for these enums, with
deserializers that emit any integer type as a u64. Switch the visit_u32
methods to visit_u64 methods to allow discriminants to have any size up
to a u64.
=> Fix hand-written enum variant deserializations to allow u64 discriminant

serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
I'm not sure why, but `std::num::Wrapping` implements `Serialize` and `Deserialize`, but only when `std` is enabled. This change allows it in the `no-std` case as well.
=> Allow serializing of Wrapping without std

serde/src/de/ignored_any.rs
This fixes the errors that occur when `IgnoredAny` is deserialized from anything containing a 128-bit integer somewhere.
As `IgnoredAny` is used in `serde_derive` to skip ignored fields in structs, these errors currently prevent deserializing structs with an ignored field containing a 128-bit integer in the input.
There's a second bug I encountered related to 128-bit integer support for untagged enums, but that one already has an issue (#1717) and a draft PR (#1719).
=> Add 128-bit integer support to de::IgnoredAny

serde/src/de/impls.rs, test_suite/tests/test_de.rs
std::time::Duration::new can panic. There is no alternative non-panicing constructor.
Check the panic condition beforehand and return an error instead of panicing.
Fixes #1933
=> Prevent panic when deserializing malformed Duration

serde/src/private/de.rs, serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/symbol.rs, serde_test/src/de.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_gen.rs
This can be especially useful together with
- `#[serde(field_identifier)]`
- `#[serde(variant_identifier)]`
- `#[serde(untagged)]` -- for that case attribute completely replaces error message
because by default they all have very generic messages.
New attribute usage:
```rust
// default message would be 
// `data did not match any variant of untagged enum OneOrMany`
#[serde(untagged, expecting = "expected single element or array of elements")]
struct OneOrMany<T> {
One(T),
Many(Vec<T>),
}
```
As two side-effects, first commit fixes panic in `assert_de_tokens_error` for enums when token stream doesn't represent an enum, so we can actually test implementation of `Deserialize`d type instead of implementation of test deserializer.
The second small improvement is adding …
=> Add new container attribute #[serde(expecting = "...")] for specifing custom expectation message

serde_derive/src/internals/case.rs, test_suite/tests/ui/rename/container_unknown_rename_rule.stderr, test_suite/tests/ui/rename/variant_unknown_rename_rule.stderr
=> Provide list of recognized rename rules on parse error

serde_test/build.rs, serde_test/src/assert.rs
Currently when error originates in the `assert_tokens` and similar functions error position pointed to location inside that helper function, which is not much helpful. This PR improves the situation is some cases. There still have cases where error location points to inside of, for example, `serde_test::ser::Serializer`, because of too many levels of calls, generated by derive macro. I don't know how to improve situation here -- maybe not panic inside of (de)serializer but to return an error?
=> Show correct location in error messages by tracking caller of utility `assert_tokens` functions

serde_test/src/configure.rs, serde_test/src/ser.rs
Two fixes in `serde_test`:
1. `assert_ser_tokens` had mixed up the expected and actual values
2. `Compact` and `Readable` wrappers didn't override `next_entry_seed` and used default implementation. Difference is noticeable for deserializers that rely on call of `next_entry_seed` (for example, quick-xml currently support only `next_entry_seed`)
=> Fix incorrect message in serializer tokens and correctly implement next_entry_seed

serde/src/private/de.rs, serde_derive/src/de.rs, serde_test/src/de.rs, test_suite/tests/expand/de_enum.expanded.rs, test_suite/tests/expand/default_ty_param.expanded.rs, test_suite/tests/expand/generic_enum.expanded.rs, test_suite/tests/expand/generic_struct.expanded.rs, test_suite/tests/expand/lifetimes.expanded.rs, test_suite/tests/expand/named_map.expanded.rs, test_suite/tests/test_de.rs, test_suite/tests/test_identifier.rs
Consider following structure:
```rust
use serde::private::de::Content;
#[serde(field_identifier)]
enum Field<'de> {
tag,
other(Content<'de>),
}
```
(This enum can be used as used field identifier of internally tagged enums)
Currently it generates following `Visitor` implementation for extracting value of the `Field`:
```rust
impl<'de> de::Visitor<'de> for FieldVisitor<'de> {
...
fn visit_u64<E>(self, value: u64) -> Result<Self::Value, E>
where
E: Error,
{
match value {
0u64 => Ok(Field::tag),
_ => Err(Error::invalid_value(Unexpected::Unsigned(value), &"field index 0 <= i < 1")),
}
}
fn visit_str<E>(self, value: &str) -> Result<Self::Value, E>
where
E: Error,
{
match value {
"tag" => Ok(Field::tag),
_ => Deserialize::deserialize(IdentifierDeserializer::from(value)).ma …
```
=> Consistently handle numeric and string/bytes keys of field names

serde_derive/src/de.rs, test_suite/tests/expand/de_enum.expanded.rs, test_suite/tests/expand/default_ty_param.expanded.rs, test_suite/tests/expand/generic_enum.expanded.rs, test_suite/tests/expand/generic_struct.expanded.rs, test_suite/tests/expand/lifetimes.expanded.rs, test_suite/tests/expand/named_map.expanded.rs, test_suite/tests/expand/void.expanded.rs
This fixes bloat introduced by #1917, as seen in https://github.com/serde-rs/serde/commit/999b94d6aee46262b883b26c9008b44bc699eedb. When the non-borrowed and borrowed fallthrough are identical, emitting them both only makes things compile slower, since the borrowed case would automatically forward to the non-borrowed case using the Visitor trait's default impl of the method.
@Mingun
=> Eliminate duplicated borrowed and non-borrowed identifier deserialization

serde/src/de/value.rs, serde/src/private/de.rs
I'm wonder, why this is not public, so just made it
=> Make impl IntoDeserializer for &[u8] public

serde/src/de/value.rs
The `derive(Debug)` on these was previously inferring a trait bounded impl like `impl<E: Debug> Debug for StringDeserializer<E>`, but the bound on `E` is unnecessary and can be avoided by a handwritten impl.
=> Eliminate inferred bound on error type of value deserializer Debug impls

serde/src/private/de.rs
This code is hit when deserializing internally tagged unions. Only some type conversions to `f32` and `f64` were allowed previously, but if you aren't in a tagged union, any number type can be converted to `f32` or `f64` (see `from_primitive.rs`).
There is a test in #1748 that now works, and I have also tested that this works in my real app.
Fixes #1748
=> Allow floats to be deserialized from ints in tagged unions

serde/build.rs, serde/src/de/impls.rs, serde/src/de/seed.rs, serde/src/de/value.rs, serde/src/lib.rs, serde/src/private/de.rs, serde/src/private/mod.rs, serde/src/private/size_hint.rs
On rustc versions between 1.13 and 1.30, the `serde` crate does not need to compile `__private::de` and `__private::ser` which are only helpers intended for the derive generated code to call. The most important effect of this is it unblocks using newer Rust features in those modules, such as `pub(crate)` syntax.
=> Omit derive helpers in versions older than serde_derive msrv

serde_derive/Cargo.toml, serde_derive/src/de.rs, serde_derive/src/internals/mod.rs, serde_derive/src/internals/receiver.rs, serde_derive/src/internals/respan.rs, serde_derive/src/lib.rs, serde_derive_internals/Cargo.toml, test_suite/tests/test_self.rs
Fixes #1506
Fixes #1565
The logic used for visiting & replacing is the same as for [async-trait's `ReplaceReceiver`](https://github.com/dtolnay/async-trait/blob/5220bbd2bdf30fa43c78d08a8e9a9f311a239cf8/src/receiver.rs#L59).
The actual implementation and test are based on pin-project's [`ReplaceReceiver`](https://github.com/taiki-e/pin-project/blob/2334cce89d860dd89620141e47bb6f2f6ea7ca75/pin-project-internal/src/utils.rs#L205-L208) and [test](https://github.com/taiki-e/pin-project/blob/2334cce89d860dd89620141e47bb6f2f6ea7ca75/tests/pin_project.rs#L710-L808). This is based on async-trait's `ReplaceReceiver`, but used in a simpler use case (type definition and a specific trait implementation) than async-trait, and same as used in this PR, except it handles `self` argument and "syn/full" …
=> Fix handling of Self keyword in type definition

serde/src/private/de.rs
Expand the fix from #1842﻿ to ContentRefDeserializer.
=> Allow floats to be deserialized from ints in untagged unions (part 2)

serde/src/private/de.rs, test_suite/tests/test_macros.rs
Added missing tests that proves that internally tagged enums can be deserialized from all serialized forms:
- Struct representation (named list of key-value pairs)
- Map representation (unnamed list of key-value pairs)
- Seq representation (unnamed list of values)
=> New internally tagged tests

serde/build.rs, serde/src/de/impls.rs, test_suite/tests/test_de.rs
`impl Add<Duration> for SystemTime` can panic. Moves to using `checked_add` instead.
Also implements #1958 for `SystemTime`, which checks the panic conditions for `std::Time::Duration::new` before calling.
Fixes #1996.
=> Prevent various panics when deserializing malformed SystemTime

serde_derive_internals/build.rs, serde_derive_internals/lib.rs
=> Build using relative path in repo if Windows lost the symlink

test_suite/tests/test_gen.rs
This feature was just stabilized in https://github.com/rust-lang/rust/pull/83799.
```console
error: the feature `non_ascii_idents` has been stable since 1.53.0 and no longer requires an attribute to enable
--> test_suite/tests/test_gen.rs:6:43
|
6 | #![cfg_attr(feature = "unstable", feature(non_ascii_idents))]
|                                           ^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> test_suite/tests/test_gen.rs:5:9
|
5 | #![deny(warnings)]
|         ^^^^^^^^
= note: `#[deny(stable_features)]` implied by `#[deny(warnings)]`
```
=> Remove non_ascii_idents feature gate from test suite

serde_derive/src/dummy.rs, test_suite/tests/expand/de_enum.expanded.rs, test_suite/tests/expand/default_ty_param.expanded.rs, test_suite/tests/expand/generic_enum.expanded.rs, test_suite/tests/expand/generic_struct.expanded.rs, test_suite/tests/expand/generic_tuple_struct.expanded.rs, test_suite/tests/expand/lifetimes.expanded.rs, test_suite/tests/expand/named_map.expanded.rs, test_suite/tests/expand/named_tuple.expanded.rs, test_suite/tests/expand/named_unit.expanded.rs, test_suite/tests/expand/ser_enum.expanded.rs, test_suite/tests/expand/void.expanded.rs
I found that this kind of `extern` only triggers `unused_extern_crates` warning: https://godbolt.org/z/bMxP8vGE9
Therefore, I think it's unnecessary to `#[allow]` the *whole* `rust_2018_idioms` lint group.
(It's causing some problems for me since I'm also using `#[forbid(future_incompatible)]`, and rust-lang/rust#83213 added some of the lints in `rust_2018_idioms` to `future_incompatible`, causing my program [fails to compile](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=60284f31914d92f2fc512885f0573b66).)
=> Allow only `unused_extern_crates` instead of the whole `rust_2018_idioms` lint group in `serde_derive`-generated code

CONTRIBUTING.md
Closes #2038.
The stuff about `test_suite/deps` is left over from prior to #1521.
=> Fix outdated test instructions in CONTRIBUTING.md

test_suite/tests/test_gen.rs
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/serde/commit/31ef747bf1e22a1279a097fb1c279d98ff549a1d#commitcomment-52641972
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/serde/commit/171db514689a0f31bb05c4c55c55219c32f7e608
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
=> spelling: implicitly

serde/build.rs
https://github.com/rust-lang/rust/pull/65251 fixed the issue where Rust was unable to support 128-bit integers on emscripten targets, that has been in Rust since 1.40 (looking at the tags on https://github.com/rust-lang/rust/commit/2bf59bea481dd4b4365cafe2e94fa8bf330a6877)
Fixes https://github.com/serde-rs/serde/issues/1995, supersedes https://github.com/serde-rs/serde/pull/2049
=> Enable 128-bit integers on emscripten post Rust 1.40

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
For 
```rust
#[serde(tag = "tag")]
enum Enum {
#[serde(deserialize_with = "de_x")]
Struct { a: u32, b: bool },
}
```
replaces overcomplicated
```rust
Field::field1 => {
struct DeserializeWith<'de> {
value: (u32, bool),
phantom: PhantomData<Enum2>,
lifetime: PhantomData<&'de ()>,
}
impl<'de> Deserialize<'de> for DeserializeWith<'de> {
fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
where
D: Deserializer<'de>,
{
Ok(DeserializeWith {
value: de_x(deserializer)?,
phantom: PhantomData,
lifetime: PhantomData,
})
}
}
Result::map(
<DeserializeWith<'de> as Deserialize<'de>>::deserialize(deserializer),
|wrap| Enum::WithStruct {
a: wrap.value.0,
b: wrap.value.1,
},
)
}
```
with much simple
```rust
Field::field1 => Result::map(de_x(deserializer), |wrap| …
```
=> Get rid of useless DeserializeWith wrapper in internally tagged enums

serde/build.rs, serde/src/ser/mod.rs
I noticed this in https://github.com/jonasbb/serde_with/blob/c578069eab2f64fd672b6dbd40068b36dd256f84/src/rust.rs#L1174 and it seems like a good idea because some iterator adapters, like `Chain`, are able to perform more efficiently in internal iteration than external iteration. See https://doc.rust-lang.org/1.54.0/std/iter/trait.Iterator.html#method.for_each.
=> Use try_fold in default implementation of collect_seq, collect_map

serde_derive/src/de.rs, serde_derive/src/pretend.rs, serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
=> Fix unaligned reference warnings on packed remote def

serde/src/lib.rs, serde/src/private/mod.rs, serde_derive/build.rs, serde_derive/src/pretend.rs, test_suite/tests/test_gen.rs
The destructuring-based implementation from #2079 is potentially problematic because not all objects can be destructured by value. For example:
```rust
#[repr(packed)]
pub struct RemotePackedNonCopy {
pub a: u16,
pub b: String,
}
#[repr(packed)]
#[serde(remote = "RemotePackedNonCopy")]
pub struct RemotePackedNonCopyDef {
a: u16,
b: String,
}
impl Drop for RemotePackedNonCopyDef {
fn drop(&mut self) {}
}
```
```console
error[E0509]: cannot move out of type `RemotePackedNonCopyDef`, which implements the `Drop` trait
--> test_suite/tests/test_gen.rs:876:10
|
876 | #[derive(Deserialize)]
|          ^^^^^^^^^^^
|          |
|          cannot move out of here
|          data moved here
|          move occurs because `__v1` has type `std::string::String`, which does not …
```
=> Support packed remote struct without destructuring

serde/src/lib.rs
Mirrored from https://github.com/serde-rs/serde-rs.github.io/pull/131.
> The [`serde_cbor`](https://github.com/pyfisch/cbor) crate [is no longer maintained](https://github.com/pyfisch/cbor/issues/179) and points to [`ciborium`](https://github.com/enarx/ciborium) as worthy successor.
=> Change cbor link to new repo

serde/src/private/mod.rs, serde_derive/src/de.rs
```rust
#![allow(dead_code)]
#![deny(unused_results)]
use serde::Deserialize; // =1.0.130
#[serde(tag = "msg", content = "data")]
enum ServerMsg {
Ping(u32),
Event {
room_id: u32,
},
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=%23!%5Ballow(dead_code)%5D%0A%23!%5Bdeny(unused_results)%5D%0A%0Ause%20serde%3A%3ADeserialize%3B%20%2F%2F%20%3D1.0.130%0A%0A%23%5Bderive(Deserialize)%5D%0A%23%5Bserde(tag%20%3D%20%22msg%22%2C%20content%20%3D%20%22data%22)%5D%0Aenum%20ServerMsg%20%7B%0A%20%20%20%20Ping(u32)%2C%0A%20%20%20%20Event%20%7B%0A%20%20%20%20%20%20%20%20room_id%3A%20u32%2C%0A%20%20%20%20%7D%2C%0A%7D)
=> Fix `unused_results` complaining rustc lint in codegen for adjacently tagged enum

serde/src/de/mod.rs, serde/src/lib.rs, serde/src/private/de.rs
=> Optimize deserialization of recursive buffered types

serde/src/de/format.rs, serde/src/de/mod.rs, test_suite/tests/test_de_error.rs
This makes the error produced by `serde::de::Visitor`'s default implementation of `visit_i128`/`visit_u128` match the format of the other integer methods' errors.
=> Render 128-bit integer value into Visitor errors

.github/workflows/ci.yml, test_suite/Cargo.toml, test_suite/build.rs, test_suite/tests/expand/de_enum.expanded.rs, test_suite/tests/expand/default_ty_param.expanded.rs, test_suite/tests/expand/generic_enum.expanded.rs, test_suite/tests/expand/generic_struct.expanded.rs, test_suite/tests/expand/generic_tuple_struct.expanded.rs, test_suite/tests/expand/lifetimes.expanded.rs, test_suite/tests/expand/named_map.expanded.rs, test_suite/tests/expand/named_tuple.expanded.rs, test_suite/tests/expand/named_unit.expanded.rs, test_suite/tests/expand/ser_enum.expanded.rs, test_suite/tests/expand/void.expanded.rs
This version contains https://github.com/eupn/macrotest/pull/78 so it will be reliable across different systems.
=> Update macrotest to 1.0.9 and enable in CI

serde/src/de/value.rs
For example `StrDeserializer::<E>::new(str)` is significantly clearer than `IntoDeserializer::<E>::into_deserializer(str)`.
=> Add constructor function for all IntoDeserializer impls

serde_test/build.rs, serde_test/src/assert.rs
Similar to https://github.com/serde-rs/serde/commit/55a7cedd737278a9d75a2efd038c6f38b8c38bd6 and https://github.com/serde-rs/serde/pull/2251, but for serde_test.
=> Invert build.rs cfgs in serde_test

serde/src/ser/impls.rs
The standard library changed orderings of `Debug` impl for atomic types from `SeqCst` to `Relaxed` in Rust 1.63 (latest stable): https://github.com/rust-lang/rust/pull/97026
This PR relaxes the orderings of `Serialize` impl for atomic types to match the latest stable.
https://github.com/serde-rs/serde/blob/ebd06eebdbbacf0c2d5beeb6ebddc77bb2e37bd4/serde/src/ser/impls.rs#L918-L919
=> Relax orderings of Serialize impl for atomic types to match the latest stable

serde/src/lib.rs
None of the error handling in serde needs the `From::from` error conversion performed implicitly by the `?` operator or the standard library's `try!` macro. This PR adds a simplified macro that gives a 5.5% improvement in compile time compared to standard `try!`, and 9% improvement compared to `?`. The same trick has already been in use by serde_derive since #1226.
| | `check` time | rmeta size | `build` time | rlib size |
|---|---|---|---|---|
| standard library `try!` | 2.15 sec | 3,568 K | 2.53 sec | 6,943 K |
| `?` operator | 2.23 sec | 3,568 K | 2.62 sec | 7,137 K |
| this PR | 2.03 sec | 3,569 K | 2.39 sec | 6,829 K |
`build` time is measured by `time rustc --cfg 'feature="std"' serde/src/lib.rs --crate-type=lib`, and `check` time is the same but with `--emit=metadata`.
=> Redefine `try` macro to omit From::from error conversion

serde/src/private/de.rs, serde/src/private/ser.rs, test_suite/tests/test_annotations.rs
Let's say we have the following enum:
```rust
#[derive(Serialize, Deserialize, Debug)]
#[serde(tag = "result", rename_all = "snake_case")]
enum Response<T> {
Success(T),
Error {
...
},
}
```
This PR makes it possible to serialize and deserialize `Response::Success(())` into and from `{"result": "success"}`. Previously, this was not possible when the type parameter `T` was `()`.
Note that this is the same behaviour as if `Response::Success` would be a unit variant, but now it can be used in a more general context.
See [This part of the docs](https://serde.rs/enum-representations.html) for a background to internally tagged enums.
It's my first time contributing to Serde, so please appologise any mistakes regarding the contribution process.
References #2302
=> Serialize and deserialize a tagged newtype variant over unit () as if it was a unit variant

serde/src/de/value.rs
This came up in https://github.com/dtolnay/serde-yaml/issues/338.
=> Add EnumAccessDeserializer to turn EnumAccess into a Deserializer

serde/src/lib.rs
https://github.com/alexcrichton/toml-rs is now archived and points towards https://github.com/toml-rs/toml
=> Update link to `toml` crate repo

serde_derive/src/de.rs, serde_derive/src/lib.rs, serde_derive/src/ser.rs, serde_derive/src/this.rs, test_suite/tests/test_remote.rs
The following already works, almost certainly by accident, but in any case we can't break it:
```rust
struct Generic<T> {
value: T,
}
#[serde(remote = "Generic::<u8>")]
struct Concrete {
value: u8,
}
```
However the turbofish in the `remote` attribute should not be necessary, since conceptually the attribute is being used to refer to a **type**, not an expression. This PR makes the attribute work as `serde(remote = "Generic<u8>")`.
Related to #2327.
=> Handle remote type written without turbofish

serde/src/de/format.rs, serde/src/de/mod.rs, serde/src/ser/impls.rs
Per https://github.com/serde-rs/serde/pull/2319#pullrequestreview-1176747235, the API enforces that the caller only wrote UTF-8 into the buffer.
This PR includes the 2 commits from #2319.
=> Revert Buf::as_str safety change from PR 2319

serde/src/de/format.rs, serde/src/de/mod.rs, serde/src/ser/impls.rs
This makes some small tweaks to the unsafe blocks to make them easier to audit:
* It changes `serde::de::Format::Buf` to be a private type since it's already not publicly exposed.
* It changes `Buf::as_str()` to be unsafe, since it relies on the caller to only write UTF-8 into the buffer.
* It adds `// Safety: ...` comments to the two callsites in `de::Visitor` that uses `Buf` to write an error message with `i128` and `u128` types.
* It converts a comment into an explicit `// Safety: ...` comment.
=> Add Safety comments to unsafe blocks

serde_derive/src/de.rs, test_suite/tests/test_remote.rs
=> Fix generated Into conversion involving generic remote derive with getter

serde/build.rs, serde/src/ser/impls.rs
Containers for the most part do not have any trait requirements for
iterating over them. So these bounds are unnecessary when Serializing
only.
=> Remove some Serialize trait bounds

serde/src/ser/impls.rs
#2333 applied to `BinaryHeap`, `HashSet` and `BTreeSet`. This PR does the equivalent change for `HashMap` and `BTreeMap` which also had trait bounds removed from their IntoIterator impl in Rust 1.34.
=> Reduce trait bounds in HashMap and BTreeMap serialize

serde/build.rs, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
I recently ran into the issue that serde didn't implement `Deserialize` for atomics when compiled for Android on Arm (`armv7-linux-androideabi`).
This was once reported in #1579 and might have been addressed back then. 
[Current version doesn't enable it for arm ever](https://github.com/serde-rs/serde/blob/3aec2a96a86d5299bd6cc57ea4840cf12f176250/serde/build.rs#L95-L111), so it's still an issue regardless.
`target_has_atomic` has become stable in Rust 1.60 (see https://github.com/rust-lang/rust/issues/32976#issuecomment-1035065937), so now it is possible to use it, at least when compiled for 1.60 and above.
I implemented it the quick way, just duplicating the code when a different cfg is enabled.
I might be able to merge those two into a single macro if that's desired.
I tested it locally …
=> Use `target_has_atomic` on Rust 1.60+ to enable atomic (de)serialization

serde/src/lib.rs, serde/src/ser/mod.rs
Without this, a user might be forced to implement 2 different duplicate traits when using serde in no-std mode.
```rust
impl serde::ser::StdError for MySerError {...}
impl core::error::Error for MySerError {...}
impl serde::Serializer for MySerializer {
type Error = MySerError;
...
}
```
=> Make StdError identical to core::error::Error on feature="unstable"

LICENSE-APACHE
All rust repos are removing this appendix, not sure why serde still has it, for more info see:
- https://github.com/rust-lang/rust/pull/67734
- https://github.com/rust-lang/miri/pull/1846
and [this comment](https://github.com/rust-lang/rust/pull/67734#issuecomment-576030746) specifically.
=> Remove appendix from LICENSE-APACHE

serde_derive/src/de.rs, test_suite/tests/test_annotations.rs
=> Make #[serde(alias)] works in #[serde(flatten)] context

serde_derive/src/de.rs
The code in these comments was supported without a feature gate in rustc 1.15.0-nightly at the time that the comments got added in #678, but was later feature gated behind `feature(never_type)` by https://github.com/rust-lang/rust/pull/39290, then by `feature(exhaustive_patterns)` in https://github.com/rust-lang/rust/pull/47630.
Closes #2379.
=> Update the comment on simpler exhaustive matching in derive

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
New `test_gen` tests prevents future regressions.
Fixes #2371.
=> Fix generation of non-existent lifetime `'de` when enum contains a #[serde(flatten)] field and a `'static` reference

serde_derive/src/internals/attr.rs
Thanks to #2390, a wrapper type around `Punctuated` is no longer needed.
=> Simplify parsing of borrow="..." attributes

serde_derive/src/internals/attr.rs, test_suite/tests/ui/borrow/empty_lifetimes.rs, test_suite/tests/ui/borrow/empty_lifetimes.stderr
Previously `serde(borrow = "")` vs `serde(borrow = " ")` were treated differently, which is unexpected. These should mean the same thing.
=> Eliminate special case on empty string passed to borrow=""

test_suite/tests/test_gen.rs
Without `serde(bound = "")`, serde_derive infers a bound of `T: Serialize` for the generated Serialize impl and `T: Deserialize<'de> + Default` for the Deserialize impl. `X` implements none of these so the generated code would fail to compile.
```console
error[E0277]: the trait bound `X: Serialize` is not satisfied
--> test_suite/tests/test_gen.rs:268:14
|
268 |     assert::<PhantomDataWrapper<X>>();
|              ^^^^^^^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `X`
|
= help: the following other types implement trait `Serialize`:
&'a T
&'a mut T
()
(T0, T1)
(T0, T1, T2)
(T0, T1, T2, T3)
(T0, T1, T2, T3, T4)
(T0, T1, T2, T3, T4, T5)
and 248 others
note: required for `PhantomDataWrapper<X>` to implement `Serialize`
--> test_suite/tests/test_gen.rs:262:14
|
262 | …
```
=> Add a test of serde(bound = "") attribute

serde_derive/src/internals/attr.rs
Similar to #2392.
This works just fine if we make syn parse `"where "` as a syn::WhereClause.
The `serde(bound = "")` attribute is definitely not common enough that it would warrant a micro-optimization.
=> Eliminate special case on empty string passed to bound=""

serde_derive/src/internals/attr.rs
This code to do `format!("where {}", string)` is from https://github.com/serde-rs/serde/commit/660ea7bd7bd0525ae07b49ff67bdeb4238c7e741 using syntex, before syn, where there was no `Parse` trait to allow parsing arbitrary data structures. Only a predetermined small set of syntax tree nodes supported being parsed.
Doing the attribute parsing with syn we no longer need to synthesize and parse a whole WhereClause, but instead just the intended syntax of the attribute.
=> Simplify parsing of where-predicates in bound attribute

serde_derive/src/internals/attr.rs
Affected by this old rustfmt problem: https://github.com/rust-lang/rustfmt/issues/3863
Currently on master, this is clearly not rustfmt-compatible formatting:
https://github.com/serde-rs/serde/blob/9af132f594e6fe8341edbfe43ee712922fbea9b1/serde_derive/src/internals/attr.rs#L470-L475
Neither is this:
https://github.com/serde-rs/serde/blob/9af132f594e6fe8341edbfe43ee712922fbea9b1/serde_derive/src/internals/attr.rs#L409-L413
=> Rearrange parts of attr.rs that rustfmt has been refusing to format

serde_derive/src/internals/attr.rs, test_suite/tests/ui/borrow/duplicate_variant.stderr
In the case of an enum like this:
```rust
enum Test<'a> {
#[serde(borrow)]
S(#[serde(borrow)] Str<'a>),
}
```
previously serde_derive's <kbd>duplicate serde attribute 'borrow'</kbd> error message would point to the first borrow attribute, the one on the variant. This PR changes it to point to the second attribute, the one on the field. This is consistent with every other situation in which the later attribute in source order is the one that gets blamed for being a duplicate.
=> Treat field-level borrow attr as duplicate of variant-level borrow attr

serde_derive/src/internals/attr.rs
This will be more suited to the next version of syn which doesn't have a `Meta` data structure any more.
Right now there is some duplication between the `Meta(Path(borrow))` case and `Meta(NameValue(borrow))` case but that will go away in the conversion.
=> Eagerly parse variant-level borrow attribute instead of deferring entire Meta

serde/build.rs, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
=> Enable CStr and CString in no-std enviroment

serde/src/lib.rs
rustc will start looking behind `#[cfg(FALSE)]` items to start giving better diagnostics. By using an explicit re-export instead of a glob export, we tell rustc that `Deserialize` and `Serialize` exist here.
I'm not sure whether it's worth it to open this PR before upstream has been merged, but since this adds minimal maintenance effort and may even make the code nicer I opened it already, feel free to wait if you prefer.
Upstream PR: rust-lang/rust#109005
=> Use explicit re-export of `serde_derive` to give rustc more info

serde/Cargo.toml, serde/src/lib.rs
I don't recall why these were hidden originally, other than this code is from the earliest days of proc macro support in rustc so probably rustdoc rendered it in an incorrect or confusing way at the time.
---
=> Show derive macros in serde's rustdoc

test_suite/tests/ui/malformed/trailing_expr.rs, test_suite/tests/ui/malformed/trailing_expr.stderr
I'm hoping to improve this error in an upcoming PR.
=> Add ui test of malformed attribute containing expression

serde_derive/Cargo.toml, serde_derive/src/internals/attr.rs, test_suite/tests/regression/issue2409.rs
=> Check for None-delimited group in attribute value

serde_derive/src/internals/attr.rs, test_suite/tests/regression/issue2415.rs
=> Accept empty #[serde()] attribute

serde_derive/src/de.rs, serde_derive/src/ser.rs
This adds a handful of `#[doc(hidden)]` attrs to make sure we don't document all of the derive serialization/deserialization internals when we use `--document-private-items`, since rustdoc now documents things inside of `const _: () = { /* ... */ };` blocks due to rust-lang/rust#104889 (which was reverted in rust-lang/rust#107083, and later re-applied in [rust-lang/rust#107000](https://github.com/rust-lang/rust/pull/107000#issuecomment-1405407485) -- so the behavior is only present on 1.69 and above).
Before:
After:
=> Make derived serializer/deserializer internals `doc(hidden)`

.gitattributes
The expand tests were removed in a649190a4d43e3ed4f5f7452ab22b7cee6ba2862, but .gitattributes still mentioned them. Because it mention only those files, I've removed it completely.
From my point of view having examples of expanded output was useful, even if they were not checked by tests, because they showed how changes in the derive macro are reflected in the generated code. But if you decide to remove them, do it completely.
=> Remove unused after .gitattributes

serde_test/src/de.rs, serde_test/src/ser.rs
Panics lead to reporting errors in tests inside of serde_test internals, returning errors moves the report location to the corresponding `assert_tokens` expression
=> Don't panic in serde_test

serde/src/private/de.rs, test_suite/tests/test_annotations.rs
This pull request will add support for `Bytes` as the tag and content field name in adjacently tagged enums. This addresses the issue raised here: https://github.com/BurntSushi/rust-csv/issues/278
Code changes are in `TagContentOtherFieldVisitor` as suggested by the investigation in the above issue, and a unit test is added to cover this case. The unit test currently fails on serde/master.
=> Allow bytes for adjacently tagged enums

serde/src/private/de.rs, serde_derive/src/de.rs
The first commit removes the one copy of the `FlatMapAccess` struct.
The third commit removes superfluous constructors of `FlatMapAccess` and `FlatStructAccess`. Since `FlatInternallyTaggedAccess` did without it, it seems to me that this is acceptable. Besides, I found that without constructors that used only in one place to construct a struct is is a little easier to understand the code.
The last two commits extracts repeated code into functions.
=> Eliminate some duplicated code

serde_derive/src/de.rs, serde_derive/src/internals/ctxt.rs, serde_derive/src/lib.rs, serde_derive/src/ser.rs
This code is from before syn::Error supported `combine`.
=> Use syn::Error's combine() API instead of Vec<syn::Error>

serde_derive/src/de.rs, serde_derive/src/internals/ast.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs, test_suite/tests/test_annotations.rs, test_suite/tests/ui/enum-representation/partially_tagged_wrong_order.rs, test_suite/tests/ui/enum-representation/partially_tagged_wrong_order.stderr
This should hopefully resolve #1402.
This can be thought of as applying the following transformation
```rust
#[derive(Serialize, Deserialize)
enum Test {
A(u32, u32),
B(u32),
C(u32),
D(u32, u32),
}
```
to
```rust
#[derive(Serialize, Deserialize)
enum TestTagged {
A(u32, u32),
B(u32),
}
#[derive(Serialize, Deserialize)
enum TestUntagged {
Tagged(TestTagged),
C(u32),
D(u32, u32)
}
#[derive(Serialize, Deserialize)
#[serde(from = "TestUntagged")]
#[serde(into = "TestUntagged")]
enum Test {
...
}
```
The actual implementation generates the implementation directly allowing it to also work efficiently for recursive enums.
The current version includes a restriction that all variants marked as `untagged` appear at the end of the enum (after …
=> Allowed Enum variants to be individually marked as untagged

serde_derive/src/de.rs, test_suite/tests/test_annotations.rs
This count should mean the number of fields expected in the serialized form, so if some fields are skipped, they shouldn't be counted.
Methods affected:
- Deserializer::deserialize_tuple
- Deserializer::deserialize_tuple_struct
- VariantAccess::tuple_variant
After this PR number of fields passed to deserializer methods will be the same as number, passed to the serializer methods.
I didn't include tests in that PR, because correct test suite should cover all possible situations, and many of them have certain problems. I plan to include a full testsuite in my upcoming PR for fixing #2105.
Right now you can see what changed in the generated code by running the following commands:
- place [skip.txt](https://github.com/serde-rs/serde/files/11585014/skip.txt) into `test_suite/tests` folder and …
=> Fix incorrect count of fields passed to tuple deserialization methods

serde/src/private/de.rs, serde_derive/src/de.rs
This PR does some minor cleanups in the code:
- Implementation of `DeserializeSeed` for `TaggedContentVisitor` is never used, so it is removed
- struct `TaggedContent` is used only in one place in the generated code, so it will be replaced by usual tuple
=> Remove unused `impl` and unnecessary struct-wrapper around tuple

serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs
=> Add `Serialize`/`Deserialize` impls for `Range{From,Full,To}`

serde_derive/src/de.rs
The first 7 commits of this PR eliminates various duplications from the code, making it more easely to understand, as I hope.
The last 3 commits makes more obvious which code is generated for different combinations of arguments. Because not all combinations are possible, after the changes impossible variants are not representable in the code.
=> Simplify code for generation of struct deserializers

serde/src/de/ignored_any.rs, serde/src/private/de.rs, test_suite/tests/test_annotations.rs
This can be useful for use-case described in #2432 (if other problems will be solved) and if you have a generic struct with flatten field and want to pass an `IgnoredAny` for whatever reason.
I also implement `PartialEq` for `IgnoredAny` so it can be tested using `assert_de_tokens`.
=> Allow to flatten `IgnoredAny`

serde/src/de/impls.rs, serde/src/private/de.rs, serde/src/private/size_hint.rs
=> Allow larger preallocated capacity for smaller elements

serde/src/private/de.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_macros.rs
Adjancently tagged enum should behave like a struct with 2 elements, the tag and the content such as
```rust 
struct Foo<'a, T> {
tag: &'a str,
content: T
}
```
This is the case for most format until you come across a format that serialize structs with fields identifier other than `&str`. for exemple auto derived struct handle the case where the field identifier is an unsigned number, or a `&[u8]`, not just `&str`. 
This is due to the fact that  `TagOrContentFieldVisitor` and `TagContentOtherFieldVisitor` directly calls `Deserializer::deserialize_str` and only handle cases for `&str`, any other format are rejected.
This PR enable `TagOrContentFieldVisitor` and `TagContentOtherFieldVisitor` to call `Deserializer::visit_identifier` and handle the case for `&str`, `&[u8]` and unsigned …
=> Add `Deserializer::deserialize_identifier` support for adjacently tagged enums

serde_derive/src/de.rs, test_suite/tests/test_de.rs
Allow to auto derive `Deserialize` generic unit structs such as 
```rust
#[derive(serde::Deserialize)]
struct Generic<const N: u8>;
```
see #2497
=> Allow `[derive(serde::Deserialize)]` for generic unit structs

precompiled/.gitignore, precompiled/Cargo.toml, precompiled/build.sh, precompiled/proc-macro2/Cargo.toml, precompiled/proc-macro2/src/lib.rs, precompiled/proc-macro2/src/watt/buffer.rs, precompiled/proc-macro2/src/watt/bytecode.rs, precompiled/proc-macro2/src/watt/mod.rs, precompiled/serde_derive/Cargo.toml, precompiled/serde_derive/build.rs, precompiled/serde_derive/main.rs, precompiled/serde_derive/src, precompiled/x86_64-unknown-linux-gnu/Cargo.toml, precompiled/x86_64-unknown-linux-gnu/README.md, precompiled/x86_64-unknown-linux-gnu/src/buffer.rs, precompiled/x86_64-unknown-linux-gnu/src/bytecode.rs, precompiled/x86_64-unknown-linux-gnu/src/lib.rs, serde_derive/src/lib.rs
```toml
[dependencies]
serde = "1"  # no features=["derive"]
serde_derive-x86_64-unknown-linux-gnu = "1.0.171-alpha.0"
```
```rust
use serde_derive::{Deserialize, Serialize};
#[derive(Deserialize, Serialize)]
pub struct MyStruct {
/* ... */
}
```
If this works, it needs to be productionized further using any of the following techniques:
- [Cosmopolitan Libc](https://github.com/jart/cosmopolitan) / αcτµαlly pδrταblε εxεcµταblε
- `[target.x86_64-unknown-linux-gnu.dependencies]` to make the macro forward to a different crate on different targets
- Precompile multiple different targets into the same crate, and detect the current platform during macro expansion time
=> Add experiment to produce precompiled builds of serde_derive

serde/src/lib.rs
In old versions of rustc (1.15 through 1.29) it would cause a warning if this #\[macro_use\] was not present.
```console
warning: proc macro crates and `#[no_link]` crates have no effect without `#[macro_use]`
--> serde/src/lib.rs:340:1
|
340 | extern crate serde_derive;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
These days serde_derive requires a newer compiler than that, so the bogus warning would never occur.
=> Delete unused serde_derive #[macro_use]

precompiled/serde_derive/src/lib.rs, serde_derive/src/internals/ast.rs, serde_derive/src/lib.rs, serde_derive_internals/lib.rs
This `allow` is from 07266233894702cb71a9ababc001dbc60f3be8cb, when serde_derive was still compatible with Rust 1.15 which did not support `dyn Trait` syntax.
=> Restore bare_trait_objects lint within serde_derive code

serde_derive/src/internals/ast.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/case.rs, serde_derive/src/internals/symbol.rs, test_suite/tests/test_macros.rs
fixes #1061 
If you don't like the style change in the second commit, I can remove it from this PR (or you can just cherry-pick the first commit).
=> Add #[serde(rename_all_fields = "foo")] attribute

serde/src/private/de.rs, serde/src/private/ser.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_macros.rs
Actually, I investigating a way of possible fixes of #1183, during which I try to narrow frontier of work as much as possible. I investigating an idea of using configurable buffer instead of generic `Content`. During that I found that generalizing of this type requires some knowledge of the `Content` internals -- `VariantDeserializer::tuple_variant` and `VariantDeserializer::struct_variant` does the matching over `Content`s content:
https://github.com/serde-rs/serde/blob/25381be0c93f32aa43ce0e399c45442965e81ecc/serde/src/private/de.rs#L1553-L1557
https://github.com/serde-rs/serde/blob/25381be0c93f32aa43ce0e399c45442965e81ecc/serde/src/private/de.rs#L1576-L1583
Here I noticed, that `MapDeserializer` and `SeqDeserializer` are different structs from the common …
=> Implement serialization of tuple variants of flatten enums

serde/src/de/mod.rs, serde/src/lib.rs
These are previous names of the `__private` module &mdash; first `serde::export` then `serde::private` then `serde::__private` &mdash; in all cases marked `doc(hidden)` and documented as not public API. Leaving a tombstone made rustc give a better diagnostic _"module is private"_ rather than _"unresolved import"_. But the rename to `__private` was 2.5 years ago in dd1f4b483ee204d58465064f6e5bf5a457543b54 so it's unlikely anyone is still benefiting from the tombstone at this point.
=> Delete tombstones of the `__private` module

serde_derive/src/de.rs
This PR makes a small refactoring which, I think, improves undertanding of the code that will be generated. During this work I found, that #2387 did not change code generation for in-place case, so the last commit fixes that. The strange thing, that tests does not catch this. I tried to see the generated code using
```console
serde\test_suite> cargo expand --test test_annotations --all-features
```
and it shows that `deserialize_in_place` method doesn't generated. I tried
- add explicit dependency to the `serde_derive` here:
https://github.com/serde-rs/serde/blob/25381be0c93f32aa43ce0e399c45442965e81ecc/test_suite/Cargo.toml#L11-L13
- add explicit requirement for the test:
```toml
[[test]]
name = "test_annotations"
required-features = ["serde_derive/deserialize_in_place"]
```
- add a new …
=> Simplify code in deserialize_in_place_struct and implement #2387 for in-place case

serde/src/private/de.rs, serde/src/private/ser.rs, serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_macros.rs
This PR is a follow on #2496.
This is a proof of concept to evaluate if such feature would be interesting. 
I've run some tests with `serde_json` and the output is the same, but still allow some format to take advantage of `variant_index` during serialization.
If it looks promising I can continue to work on it
=> Revisit of the representation of adjacently tagged enums tag

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, test_suite/tests/test_annotations.rs, test_suite/tests/test_identifier.rs
This PR fixes two problems:
- The first one is that aliases seems to be sorted in the expecting message because their are collected from `BTreeSet`, but after adding a main name to the sorted list of aliases it is not sorted anymore
- The second one is that `#[serde(field_identifier)]` and `#[serde(variant_identifier)]` does not include aliases in their default expecting message.
I've updated tests for identifiers and fix both problems. I put them into one PR because the first problem affects the newly added test for aliases for the second problem.
The last 4 commits are small refactoring that slightly reduces number of clones and optimizes generation.
=> Keep aliases always sorted and include aliases in expecting message for field/variant_identifier

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, test_suite/tests/ui/default-attribute/enum.stderr, test_suite/tests/ui/default-attribute/enum_path.stderr, test_suite/tests/ui/default-attribute/nameless_struct_fields.rs, test_suite/tests/ui/default-attribute/nameless_struct_fields.stderr, test_suite/tests/ui/default-attribute/nameless_struct_fields_path.rs, test_suite/tests/ui/default-attribute/nameless_struct_fields_path.stderr, test_suite/tests/ui/default-attribute/tuple_struct.rs, test_suite/tests/ui/default-attribute/tuple_struct.stderr, test_suite/tests/ui/default-attribute/tuple_struct_path.rs, test_suite/tests/ui/default-attribute/tuple_struct_path.stderr
Right now you cannot place `#[serde(default)]` at tuple struct, although it is possible to mark individual fields as `#[serde(default)]`:
```rust
struct Tuple(
// possible, but make no sense in that case, because if
// field will be set to default value that means that sequence
// is exhausted and the next field will fail to deserialize
#[serde(default)] u8,
u8,
);
#[serde(default)] // impossible, but make sense
struct Tuple(
#[serde(default)] u8,
u8,
);
```
This PR fixes that and also guaranties that tuple structs will always have a trail of defaulted non-skipped fields as soon as first defaulted field is appear.
=> Allow `#[serde(default)]` on tuple structs

serde/src/de/impls.rs
This allows to deserialize `Box<OsStr>`.
=> Add forward impl for OsStr

serde_derive/src/de.rs
This PR makes a small refactoring in order to remove complexity in `deserialize_generated_identifier` about determining `ignore_variant` and `fallthrough` values. Because both values depends only on input parameters, I moved they determination from `deserialize_generated_identifier` to the calling functions. Thus, it is easier to understand which pairs of parameters are possible
=> Refactor code that generates `__Field` enums

serde/src/private/ser.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/symbol.rs, serde_derive/src/ser.rs, test_suite/tests/test_remote.rs
Serde already supports a `serde(skip)` attribute to not serialize a particular variant, returning an error instead.
```rust
#[derive(Serialize)]
enum Enum {
Foo,
#[serde(skip)]
Bar,
}
```
This PR gives equivalent behavior to #\[non_exhaustive\] remote enums: it's as if every other possible variant were listed with a `serde(skip)` on it.
```rust
#[serde(remote = "std::io::ErrorKind")]
#[non_exhaustive]
enum ErrorKindDef {
NotFound,
PermissionDenied,
// ...
}
```
```rust
assert!(ErrorKindDef::serialize(&ErrorKind::OutOfMemory, serializer).is_err());
```
Closes #2360. Closes #2361.
=> Treat unmatched non-exhaustive remote variant as serde(skip)

.github/workflows/ci.yml
https://github.com/rust-lang/cargo/issues/12419 has been fixed (https://github.com/rust-lang/cargo/pull/12454) and landed in nightly (https://github.com/rust-lang/rust/pull/114773).
=> Adopt `cargo rm` after Cargo bugfix

serde_derive/src/ser.rs, test_suite/tests/test_remote.rs
=> Fix "cannot move out of *self which is behind a shared reference"

serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
Found a few places where `&Vec<T>` is used and could be swapped with `&[T]`.
=> Fix: Use `&[T]` instead of `&Vec<T>` wherever possible

serde/Cargo.toml
Followup to #2588.
The "=1.0.185" under `target.'cfg(any())'.dependencies` should be enough to constrain the versions.
=> Duplicate the serde_derive dependency version in one fewer place

Cargo.toml
This makes the git repository incompatible with Rust 1.45 through 1.50, as `resolver` was introduced unstably in 1.45 and stabilized in 1.51. But that's fine and the published serde crate won't be affected.
=> Adopt new Cargo feature resolver

serde/src/lib.rs
The `csv` crate is from BurntSushi.
=> Add CSV to the formats list

serde_derive/src/de.rs, test_suite/tests/test_annotations.rs
This produces an error:
```rust
#[serde(tag = "t")]
enum Data {
A,
Var(u32),
}
```
```
error[[E0282]](https://doc.rust-lang.org/stable/error_codes/E0282.html): type annotations needed
--> src/lib.rs:3:10
|
3 | #[derive(Deserialize)]
|          ^^^^^^^^^^^ cannot infer type
|
= note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0282`.
error: could not compile `playground` (lib) due to previous error
```
My proposed fix is intended to minimize changes to code unrelated to the changes from #2403.
=> "cannot infer type" from Deserialize derive macro with simple variants and untagged variants

serde/build.rs, serde/src/de/impls.rs, test_suite/tests/test_de.rs
`f32 as f64` and `f64 as f32`, if the input is NaN, produces an output NaN with nondeterministic sign. This leads to bugs like TOML `+nan` and `-nan` and YAML `.nan` and `-.nan` being deserialized to f32 with the wrong sign nondeterministically because they're manipulated as f64 internally by the library's Value type.
See https://github.com/rust-lang/miri/issues/3139.
=> Ensure f32 deserialized from f64 and vice versa preserve NaN sign

serde/src/de/impls.rs
closes #2652
**Issue TL;DR**
RangeFrom and RangeTo implementations seems to have been switched around and RangeFrom was expecting a 'end' field when it should be expecting a 'start' field.
=> Fix Range{From,To} deserialize mixup

serde/src/lib.rs, serde_derive/src/lib.rs
This lint got downgraded from `pedantic` to `nursery` by https://github.com/rust-lang/rust-clippy/pull/7568 so we no longer run it.
=> Remove option_if_let_else clippy suppression

serde_derive/src/bound.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/receiver.rs
Context: https://github.com/dtolnay/syn/issues/1522
=> Pick up changes to non_exhaustive_omitted_patterns lint

Cargo.toml, serde_derive/Cargo.toml, serde_derive_internals/Cargo.toml
I've only added the dependencies as workspace dependencies to make it easier to maintain from now on.
I've executed in the `serde` directory.
```sh
$ cargo test --features derive
```
And in the `test_suite`:
```sh
cargo +nightly test --features unstable
```
Both worked fine.
As required in the https://github.com/serde-rs/serde/blob/111803ab0768d010c606f2fc0d0add12750d5eef/CONTRIBUTING.md
=> Adding workspace dependencies

Cargo.toml, serde_derive/Cargo.toml, serde_derive_internals/Cargo.toml
Since #2678 all Cargo commands have been reporting this warning:
```console
warning: serde_derive_internals/Cargo.toml: `default-features` is ignored for syn,
since `default-features` was not specified for `workspace.dependencies.syn`, this
could become a hard error in the future
```
=> Fix workspace.dependencies default-features future compat warning

serde/src/de/mod.rs, serde/src/de/value.rs, test_suite/tests/test_value.rs
Apparently `write!` generates more code than `write_str` when used with a simple string, so optimizing it.
=> A few minor `write_str` optimizations

serde/src/private/de.rs, test_suite/tests/test_macros.rs
The test that is fixing by this PR was introduces in #933 and has a purpose to reach the `Content::Str` case here that was fixed by that PR:
https://github.com/serde-rs/serde/blob/05a5b7e3c6de502d45597cbc083f28bc1d4f4626/serde/src/private/de.rs#L1446
The `Content::Str` case here produced using `visit_borrowing_str` here (that the only case when `Content::Str` can be created):
https://github.com/serde-rs/serde/blob/05a5b7e3c6de502d45597cbc083f28bc1d4f4626/serde/src/private/de.rs#L424-L429
which is called as a response to `Token::BorrowedStr`:
https://github.com/serde-rs/test/blob/d1294b3ad549874d5035752ac62b4eb75cee5060/src/de.rs#L129
However, unit variants of externally tagged enum cannot be deserialized from the string token by itself. The one of following combinations of tokens should …
=> Use correct tokens in test to represent an enum variant

serde/src/ser/mod.rs
At least this seems to be how serde_derive behaves:
https://github.com/serde-rs/serde/blob/3f43fca90dfff4a8728765867cea85865843c337/serde_derive/src/ser.rs#L335-L341
Explicitly documenting this makes it easier for custom `Serializer` implementations to know what to expect from the `len` value, and makes it clearer for custom `Serialize` implementations to know what to provide as value.
=> Document that `len` does not include skipped struct fields

serde/build.rs, serde/src/de/impls.rs, serde/src/lib.rs, serde/src/ser/impls.rs, test_suite/tests/test_de.rs, test_suite/tests/test_ser.rs
This implementation is heavily inspired by the existing trait implentation for `std::num::Wrapping<T>`.
fix #2708
=> Implement Ser+De for Saturating<T>

serde/src/de/impls.rs
Followup to #2709. This also adds support for Saturating\<i128\> and Saturating\<u128\>.
=> Integrate Saturating<T> deserialization into impl_deserialize_num macro

serde/src/macros.rs
Hit in [`serde-save`](https://docs.rs/serde-save), the following code fails to compile:
```rust
enum Value {
Error,
}
impl<'de> serde::Deserializer<'de> for Value {
type Error = serde::de::value::Error;
fn deserialize_any<V>(self, _: V) -> Result<V::Value, serde::de::value::Error>
where
V: serde::de::Visitor<'de>,
{
todo!()
}
serde::forward_to_deserialize_any! {
bool i8 i16 i32 i64 i128 u8 u16 u32 u64 u128 f32 f64 char str string
bytes byte_buf option unit unit_struct newtype_struct seq tuple
tuple_struct map struct enum identifier ignored_any
}
}
```
```console
error: ambiguous associated item
--> src/lib.rs:16:5
|
16  | /     serde::forward_to_deserialize_any! {
17  | |         bool i8 i16 i32 i64 i128 u8 u16 u32 u64 u128 f32 f64 char str string
18  | |         bytes byte_buf option …
```
=> fix: ambiguous associated item in forward_to_deserialize_any!

serde/src/de/mod.rs, test_suite/tests/test_de_error.rs
bef110b92a1 changed the display for unexpected floats to always append a
".0" if there was no decimal point found in the formatting of the float.
However, this should only be relevant for finite (i.e., not NaN or inf)
values.  The change introduced a test failure in the ordered-float
crate due to this:
---- impl_serde::test_fail_on_nan stdout ----
thread 'impl_serde::test_fail_on_nan' panicked at 'assertion failed: `(left == right)`
left: `Error { msg: "invalid value: floating point `NaN.0`, expected float (but not NaN)" }`,
right: `"invalid value: floating point `NaN`, expected float (but not NaN)"`', src/lib.rs:1554:9
stack backtrace:
0: rust_begin_unwind
at /usr/src/rustc-1.70.0/library/std/src/panicking.rs:578:5
1: core::panicking::panic_fmt
at …
=> Only format Unexpected::Float with decimal point if it is finite

serde/build.rs, serde_derive/Cargo.toml, serde_derive/build.rs, serde_derive/src/lib.rs, serde_derive_internals/build.rs, serde_derive_internals/lib.rs, test_suite/tests/test_de_error.rs
Context: https://blog.rust-lang.org/2024/05/06/check-cfg.html
=> Resolve unexpected_cfgs warning

serde_derive/src/internals/attr.rs
=> Provide public access to RenameAllRules in serde_derive_internals

serde/Cargo.toml, serde/build.rs, serde/src/de/impls.rs, serde/src/de/mod.rs, serde/src/de/value.rs, serde/src/lib.rs, serde/src/ser/impls.rs
As of recently, docs.rs defines a `docsrs` configuration for all builds, so we no longer need to do it using our own `package.metadata.docs.rs.rustdoc-args`.
=> Rely on docs.rs to define --cfg=docsrs by default

serde/build.rs, serde/src/de/mod.rs, serde/src/ser/mod.rs
This change enables the `#[diagnostic::on_unimplemented]` attribute for the `Serialize` and `Deserialize` trait to point the user to the relevant derives and point out that they might want to check crates features for external types by adding the relevant hints an note.
The help text is up for discussion, but I feel that this might help quite a lot of users that struggle why external crates do not implement the serde traits.
=> Use the `#[diagnostic::on_unimplemented]` attribute when possible

test_suite/tests/ui/on_unimplemented.rs, test_suite/tests/ui/on_unimplemented.stderr
Test the diagnostic created by https://github.com/serde-rs/serde/pull/2767.
=> Add ui test of unsatisfied serde trait bound

serde/src/private/ser.rs
Serializers that reimplements serialize_entry will get benefits from that
=> Use serialize_entry instead of serialize_key + serialize_value when serialize flatten newtype enum variant

serde_derive/src/de.rs, test_suite/tests/test_gen.rs
Fixes #2789.
For the enum in the repro:
```rust
enum Inner<'a> {
Default {
s: &'a str,
},
Builder {
s: &'a str,
#[serde(flatten)]
o: Options,
},
}
```
we would previously collect a `Vec<Option<(Content, Content)>>` of the unrecognized keys and values in the input. These would be used for deserializing `o` inside `Builder`, but when deserializing `Default`, the vector would not be used and would correctly trigger the _"collection is never read"_ warning.
=> Skip collecting unmatched fields in variants that do not use flatten

serde_derive/src/de.rs, serde_derive/src/internals/ast.rs, serde_derive/src/internals/attr.rs, test_suite/tests/regression/issue1904.rs, test_suite/tests/regression/issue2565.rs, test_suite/tests/regression/issue2792.rs, test_suite/tests/test_annotations.rs
Store `has_flatten` mark in the `Variant` attributes and use it instead of `attr::Container::has_flatten()` in methods that can be called for variants.
Fixes #1904, fixes #2565, fixes #2792
=> Correctly process flatten fields in enum variants

test_suite/tests/test_gen.rs
@Mingun, this lint fires since #2567. Could you take a look at what should be generated for such a struct?
https://github.com/serde-rs/serde/blob/fc55ac70d34221b38672b1583e496011fbae92aa/test_suite/tests/test_gen.rs#L723-L727
```console
error: collection is never read
--> test_suite/tests/test_gen.rs:723:25
|
723 |     #[derive(Serialize, Deserialize)]
|                         ^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collection_is_never_read
note: the lint level is defined here
--> test_suite/tests/test_gen.rs:23:9
|
23  | #![deny(clippy::collection_is_never_read)]
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace …
```
=> Temporarily ignore collection_is_never_read on FlattenSkipDeserializing

serde_derive/src/de.rs, serde_derive/src/internals/ast.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs, test_suite/tests/test_gen.rs
This PR removes workaround from #2794 in the first commit.
The 2nd commit unifies behaviour for all cases where flatten fields processed in the deserializer. Consequence of that commit: `FlattenSkipDeserializing[DenyUnknown]`
- does not collect data in `Field`, because do not read them anyway
- gets `deserialize_in_place` method
- gets ability to deserialize from sequence (`visit_seq` method)
- uses `deserialize_struct` instead of `deserialize_map`
The 3rd commit gives understandable message when derive failed due to assertion.
The 4th commit removed dead code that here since 2018.
The last commit does the unification of `has_flatten` behaviour for the serializer side. Consequence of that commit: `FlattenSkipSerializing`
- uses `serialize_struct` instead of `serialize_map`
=> `has_flatten` rework

serde/src/private/de.rs, serde/src/private/ser.rs, test_suite/tests/test_annotations.rs
=> Support (de-)serializing flattened unit struct

serde/src/de/impls.rs, serde/src/ser/impls.rs
Followup to #2816. These impls no longer need a cfg banner on docs.rs.
=> Delete doc(cfg) attribute from impls that are supported in no-std

serde/build.rs, serde/src/de/mod.rs, serde/src/lib.rs, serde/src/ser/mod.rs
https://github.com/serde-rs/serde/issues/812#issuecomment-2332393343
=> Stabilize no-std Error trait

serde/src/private/de.rs
Closures capture every type parameter that is in scope, even ones which cannot make a difference to the behavior of the closure. This was previously causing a whole new MapDeserializer to be monomorphized for every distinct Visitor type that we deserialize from Content or &amp;Content (i.e. internally tagged and untagged enums).
Tested by measuring the size of the rlib produced from the following small library. `cargo clean && cargo build --release && ls -l target/release/librepro.rlib`
```rust
use serde::Deserialize;
pub enum Untagged {
A {},
B {},
}
pub fn from_str(json: &str) -> serde_json::Result<Untagged> {
serde_json::from_str(json)
}
```
Before this PR: 127K. After this PR: 111K. This is 12% smaller.
=> Eliminate closures capturing needlessly many type parameters

serde/src/private/de.rs
This is a good suggestion from https://github.com/serde-rs/serde/pull/2821#pullrequestreview-2288334462. I was not able to measure any binary size improvement &mdash; the rlib is 111K before and after. But it's worth making the change.
=> Remove explicit ContentDeserializer construction in visit functions

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs, test_suite/tests/ui/default-attribute/incorrect_type_enum_adjacently_tagged.rs, test_suite/tests/ui/default-attribute/incorrect_type_enum_adjacently_tagged.stderr, test_suite/tests/ui/default-attribute/incorrect_type_enum_externally_tagged.rs, test_suite/tests/ui/default-attribute/incorrect_type_enum_externally_tagged.stderr, test_suite/tests/ui/default-attribute/incorrect_type_enum_internally_tagged.rs, test_suite/tests/ui/default-attribute/incorrect_type_enum_internally_tagged.stderr, test_suite/tests/ui/default-attribute/incorrect_type_enum_untagged.rs, test_suite/tests/ui/default-attribute/incorrect_type_enum_untagged.stderr, test_suite/tests/ui/default-attribute/incorrect_type_newtype.rs, test_suite/tests/ui/default-attribute/incorrect_type_newtype.stderr, test_suite/tests/ui/default-attribute/incorrect_type_struct.rs, test_suite/tests/ui/default-attribute/incorrect_type_struct.stderr, test_suite/tests/ui/default-attribute/incorrect_type_tuple.rs, test_suite/tests/ui/default-attribute/incorrect_type_tuple.stderr, test_suite/tests/ui/default-attribute/union.rs, test_suite/tests/ui/default-attribute/union.stderr, test_suite/tests/ui/default-attribute/union_path.rs, test_suite/tests/ui/default-attribute/union_path.stderr, test_suite/tests/ui/default-attribute/unit.rs, test_suite/tests/ui/default-attribute/unit.stderr, test_suite/tests/ui/default-attribute/unit_path.rs, test_suite/tests/ui/default-attribute/unit_path.stderr, test_suite/tests/ui/with/incorrect_type.rs, test_suite/tests/ui/with/incorrect_type.stderr
This PR changes the errors reported by `rustc` when signature of function specified in
- `#[serde(with = "...")]` 
- `#[serde(deserialize_with = "...")]`
- `#[serde(serialize_with = "...")]`
- `#[serde(default = "...")]`
is wrong. With this PR error will point to the `"..."`.
=> Improve error reporting about mismatched signature in `with` and `default` attributes

serde_derive/src/de.rs, test_suite/tests/test_annotations.rs
Before that PR an error message of such enum did not include aliases of possible variants:
```rust
enum Enum {
#[serde(alias = "C")]
A,
B
}
```
Now the error message will mention `C`
=> Show variant aliases in error message

test_suite/tests/ui/with/incorrect_type.stderr
This test was failing on master since the stderr in #2558 had been generated prior to 8e1ae68569db46251a88997e5e212392d4ad83ea.
https://github.com/serde-rs/serde/pull/2558#issuecomment-2427872479
=> Update ui tests from PR 2558

serde_derive/src/dummy.rs
Clippy is reporting warnings in serde_derive-generated code in master because https://github.com/serde-rs/serde/pull/2558 interferes with clippy's `is_from_proc_macro` logic. The generated code is the same before and after that PR, but the PR makes it use spans that hide that particular tokens are generated. For example in the case of:
```rust
use serde::{Serialize, Serializer};
#[derive(Serialize)]
pub struct Struct {
#[serde(serialize_with = "serialize_string")]
pub i: i32,
}
fn serialize_string<S>(i: &i32, serializer: S) -> Result<S::Ok, S::Error>
where
S: Serializer,
{
serializer.collect_str(i)
}
```
```console
$ cargo clippy
warning: the following explicit lifetimes could be elided: '__a
--> src/main.rs:3:10
|
3 | #[derive(Serialize)]
|          ^^^^^^^^^
|
= help: for further …
```
=> Ignore needless_lifetimes clippy lint in generated code

serde_derive/src/dummy.rs, serde_derive/src/ser.rs
This leaves more of the generated code accurately identified as generated, avoiding the `dead_code` and `needless_lifetimes` warnings that originated from #2558.
=> Reduce scope of quote_spanned on SerializeWith wrapper

serde_derive/src/de.rs
Followup to the second commit of #2566. The original naming `field_names_idents` used to make sense when the contents were a tuple of field name (&amp;str) and ident. It was changed to a 3-tuple of field name, ident, aliases by #1458 without renaming any variables. Then the field name was removed by #2566, leaving ident and aliases.
Maybe a struct instead of a tuple would be more suitable.
=> Rename field_names_idents -> field_idents_aliases

serde_derive/src/de.rs, serde_derive/src/ser.rs, test_suite/tests/regression/issue2844.rs, test_suite/tests/ui/with/incorrect_type.stderr
=> Fix hygiene of macro-generated local variable accesses in serde(with) wrappers

serde_derive/src/de.rs, test_suite/tests/regression/issue2846.rs
=> Hygiene for macro-generated newtype struct deserialization with `with` attr

serde/src/de/value.rs
Unfortunately, blanket implementation `IntoDeserializer for Deserializer` is impossible right now because this would be a breaking change. External crates may have this such implementation (and serde_json actually have it for `Value`).
Closes #2498
=> Implement `IntoDeserializer` for all `Deserializer`s in `serde::de::value` module

serde_derive/src/internals/check.rs, test_suite/tests/ui/conflict/alias-enum.rs, test_suite/tests/ui/conflict/alias-enum.stderr, test_suite/tests/ui/conflict/alias.rs, test_suite/tests/ui/conflict/alias.stderr
- Check that alias is not the same as name of other field / variant (it still can be the name of owning field / variant)
- Check that aliases are unique, i. e. two different fields / variants does not use the same alias
It would be better, if error points to corresponding alias, but currently alias spans are not stored anywhere, so I left this to another PR.
Fixes #2308, fixes #2551
=> Add checks for conflicts for aliases

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/internals/check.rs, serde_derive/src/internals/mod.rs, serde_derive/src/internals/name.rs, serde_derive/src/ser.rs
Closes #2308.
```console
warning: unreachable pattern
--> src/main.rs:7:22
|
5 |     #[serde(rename = "Response")]
|                      ---------- matches all the relevant values
6 |     Request { id: String},
7 |     #[serde(rename = "Response")]
|                      ^^^^^^^^^^ no value can reach this
|
= note: `#[warn(unreachable_patterns)]` on by default
```
=> Produce unreachable_patterns warning when deserialization names collide

serde_derive/src/internals/check.rs, test_suite/tests/ui/conflict/alias-enum.rs, test_suite/tests/ui/conflict/alias-enum.stderr, test_suite/tests/ui/conflict/alias.rs, test_suite/tests/ui/conflict/alias.stderr
- #2562
- #2853
Since #2855 there is an `unreachable_patterns` warning instead.
=> Revert the colliding aliases hard error (PRs #2562 & #2853)

serde_derive/src/de.rs
When using `cargo llvm-cov` on one of my projects I noticed that the `#[derive(Deserialize)]` annotations on my structs were marked as not covered.
This PR adds `#[automatically_derived]` also to the `impl de::Visitor` blocks that are generated. In my tests, they now no longer show up in the coverage as not covered.
`rustc` automatically excludes `impl` blocks marked with `#[automatically_derived]` since https://github.com/rust-lang/rust/pull/120185. 
The generated `impl Deserialize` block is already marked with `#[automatically_derived]` and thus correctly not counted.
However, the visitors and field visitors which are generated within the `deserialize` method were counted towards the coverage.
=> Mark generated `impl de::Visitor` blocks as `#[automatically_derived]`

serde_derive/src/de.rs, serde_derive/src/ser.rs
Followup to https://github.com/serde-rs/serde/pull/2866.
=> Mark all generated trait impls as #[automatically_derived]

serde/src/private/ser.rs, test_suite/tests/test_annotations.rs
Unit variant of externally tagged enum can be deserialized when enum is flatten, [but cannot be serialized](
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67545ca025699ac9894f464ad1dc2405) -- `ser` test failed:
```rust
#![cfg(test)]
use serde::{Deserialize, Serialize}; // 1.0.204;
use serde_json::{from_str, to_string}; // 1.0.121
#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Flatten {
#[serde(flatten)]
data: Enum,
}
#[derive(Debug, PartialEq, Serialize, Deserialize)]
enum Enum {
Unit,
}
const JSON: &str = r#"{"Unit":null}"#;
#[test]
fn de() {
// ok
assert_eq!(from_str::<Flatten>(JSON).unwrap(), Flatten { data: Enum::Unit });
}
#[test]
fn ser() {
// called `Result::unwrap()` on an `Err` value: Error("can only flatten structs and maps (got an enum)", …
```
=> Fix roundtrip of flatten externally tagged enum unit variant

serde/Cargo.toml, serde_derive/Cargo.toml, serde_derive_internals/Cargo.toml
Without this, standard library doc links end up going to https://doc.rust-lang.org/nightly/std just because docs.rs's builders use a nightly rustc.
=> Point standard library links to stable

serde_derive/Cargo.toml, serde_derive_internals/Cargo.toml
I missed this in #2895.
https://docs.rs/serde_derive/1.0.218/src/serde_derive/lib.rs.html#91
=> Also link to stable proc_macro

serde_derive/src/dummy.rs
First attempt https://github.com/serde-rs/serde/pull/2905 failed because [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=71f25171e7d282a7073985c1f34eb6ef) pattern apparently doesn't work. Alternatively one could replace `_serde` with a runtime `#path`
Fixes https://github.com/serde-rs/serde/issues/2904
=> fix clippy absolute paths warning

serde_derive/src/ser.rs
=> chore: fix the incorrect symbol

.github/workflows/ci.yml
I am blindly guessing that this whitespace is what is causing PRs to bounce from the merge queue despite all checks passing.
<p align="center"><img src="https://github.com/user-attachments/assets/f3760a3d-e4bf-4876-bd8b-8dc35bfb6c81" width="700"></p>
=> Drop trailing whitespace from CI job name

README.md, test_suite/Cargo.toml, test_suite/no_std/Cargo.toml
Updated the Cargo.toml files for test suites and a link in the README to use Rust edition 2021 instead of 2018. This ensures compatibility with the 2021 Rust features and standards.
=> Update a Rust edition to 2021 across project files

serde/src/de/mod.rs, serde/src/lib.rs, serde/src/private/de.rs
> This sounds like a change we could do on master and consider in isolation from this PR
As posted by @oli-obk in https://github.com/serde-rs/serde/pull/2608#discussion_r1810195461, this PR removes `actually_private::T` type from signature of the hidden `Deserializer::__deserialize_content` method, like `Visitor::__private_visit_untagged_option` does not have such guard:
https://github.com/serde-rs/serde/blob/2130ba57885357b56e7087e164a33be0288371e4/serde/src/de/mod.rs#L1679-L1687
This guard just makes life harder in some cases without real benefits. If you use private API you already understand consequences and them can be totally acceptable, especially if you depend on the specific version
=> Remove `actually_private::T`

serde/Cargo.toml
Making Result impls get disabled when using `serde = { version = "1", default-features = false }` would have been a breaking change.
=> Forcibly enable serde_core/result when using serde

Cargo.toml
Without this, there end up being 2 incompatible `serde_core` versions, one from crates.io used by dependencies such as serde_json and trybuild, and one from the local repo.
```console
error[E0277]: the trait bound `cargo::Metadata: serde::Deserialize<'de>` is not satisfied
--> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/trybuild-1.0.111/src/cargo.rs:183:5
|
183 |     serde_json::from_slice(&output.stdout).map_err(|err| {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound
|
help: the trait `serde_core::de::Deserialize<'_>` is not implemented for `cargo::Metadata`
--> $CARGO_HOME/registry/src/index.crates.io-1949cf8c6b5b557f/trybuild-1.0.111/src/cargo.rs:14:1
|
14 | pub(crate) struct Metadata {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^
= note: for local types consider …
```
=> Patch serde_core at workspace level

serde/src/integer128.rs
This macro has no effect on any version of Serde released in the past 2 years. It was used long ago in crates that needed to support Rustc older than 1.26.0, or Emscripten targets older than 1.40.0, which did not yet have 128-bit integer support. These days Serde requires a Rust compiler newer than that so 128-bit integers are always supported.
=> Deprecate serde_if_integer128 macro

serde_derive/src/ser.rs
In the 2024 edition of Rust, `serde`'s macros for `serialize_with` can lead to a temporary lifetime error such as:
```
error[E0716]: temporary value dropped while borrowed
--> my-binary/src/main.rs:6:10
|
6 | #[derive(MyDerive)]
|          ^^^^^^^-
|          |      |
|          |      temporary value is freed at the end of this statement
|          creates a temporary value which is freed while still in use
|          borrow later used by call
|          in this derive macro expansion
|
::: /private/tmp/life/my-project/my-macro/src/lib.rs:6:1
|
6 | pub fn my_derive(_input: TokenStream) -> TokenStream {
| ---------------------------------------------------- in this expansion of `#[derive(MyDerive)]`
|
= note: consider using a `let` binding to create a longer lived value
```
This is …
=> Fix temporary value lifetime in `serialize_struct`

serde_core/src/lib.rs
Fixes https://github.com/serde-rs/serde/issues/2977.
Maybe it would be possible to redirect trait definitions from docs.rs/serde_core to docs.rs/serde as the canonical location using something like this in `--html-in-header`:
```html
<script>
url_regex = /^https:\/\/docs\.rs\/serde_core\/([^\/]+)\/serde_core\/(.+)$/;
serde_redirect = window.location.href.replace(url_regex, "https://docs.rs/serde/$1/serde/$2");
if (serde_redirect !== window.location.href) {
window.location.replace(serde_redirect);
}
</script>
```
=> Change serde_core's html_root_url to docs.rs/serde_core

serde/build.rs, serde/src/private/de.rs, serde/src/private/ser.rs, serde_core/src/private/doc.rs, serde_core/src/private/seed.rs, test_suite/tests/ui/with/incorrect_type.stderr
Rustc was suggesting these private types in diagnostics, with paths like `_::_serde::__private::ser::content::ContentSerializer<E>`.
=> Mark every trait impl for a private type with do_not_recommend

serde_derive/src/de.rs, serde_derive/src/internals/attr.rs, serde_derive/src/ser.rs
In other places `_serde` name is used to access the `serde` crate, so will be defined and can be use there
=> Unify access to the serde namespace

serde_derive/src/de.rs
Adjacently tagged enums with many struct variants should get most benefit from that.
=> Remove code duplication when deriving Deserialize for adjacently tagged enums

serde/src/lib.rs
The `#[macro_use]` attribute makes the module's macros usable from inside the same crate. This used to be needed when Serde contained invocations of `serde_if_integer128!` prior to #2600, but no longer.
The macro remains usable from outside of the crate.
=> No longer macro_use integer128 module

serde_core/src/de/mod.rs
This struct was added into `serde_core::de` by https://github.com/serde-rs/serde/pull/2608 when it was not previously exposed by `serde::de`. I saw this in the review and tried to remove it in #2962/#2969 but 5ac3d84d999532a26ee036620fdc84760ba05c45 was incomplete.
I am not opposed to exposing a helper in some form, maybe even this form, just not silently as part of an unrelated refactor. It would need a dedicated PR with use case.
`deserialize_in_place` is niche functionality so it is unlikely that someone has immediately come to rely on the `InPlaceSeed` type since then.
=> Remove InPlaceSeed public re-export

serde/build.rs, serde_core/build.rs, serde_core/src/crate_root.rs
=> Workaround for RUSTDOCFLAGS='--cfg=docsrs'
